# <b><font color='forestgreen'>Знакомство с Polars</font></b>
[User_guide](https://docs.pola.rs/)<br>
[Cheet_Sheet_Pandas_to_Polars](https://www.rhosignal.com/posts/polars-pandas-cheatsheet/)

### <font color='forestgreen'>1. Установка библиотеки Polars</font>

In [1]:
# Для Polars требуется Python 3.7. и выше
!python --version

Python 3.13.6

In [2]:
# Скачивание polars
! pip install polars

Collecting polars
  Downloading polars-1.40.1-py3-none-any.whl.metadata (10 kB)
Collecting polars-runtime-32==1.40.1 (from polars)
  Downloading polars_runtime_32-1.40.1-cp310-abi3-win_amd64.whl.metadata (1.5 kB)
Downloading polars-1.40.1-py3-none-any.whl (828 kB)
   ---------------------------------------- 0.0/828.7 kB ? eta -:--:--
   ---------------------------------------- 828.7/828.7 kB 13.5 MB/s  0:00:00
Downloading polars_runtime_32-1.40.1-cp310-abi3-win_amd64.whl (51.8 MB)
   ---------------------------------------- 0.0/51.8 MB ? eta -:--:--
   -------- ------------------------------- 11.5/51.8 MB 57.0 MB/s eta 0:00:01
   -------------------- ------------------- 26.0/51.8 MB 64.3 MB/s eta 0:00:01
   -------------------------------- ------- 41.7/51.8 MB 68.8 MB/s eta 0:00:01
   ---------------------------------------  51.6/51.8 MB 71.0 MB/s eta 0:00:01
   ---------------------------------------- 51.8/51.8 MB 63.8 MB/s  0:00:00
Installing collected packages: polars-runtime-32, polars

   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   ---------------------------------------- 2/2 [polars]

Successfully installed polars-1.40.1 polars-runtime-32-1.40.1

In [3]:
# Скачивание pyarrow
! pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-24.0.0-cp313-cp313-win_amd64.whl.metadata (3.0 kB)
Downloading pyarrow-24.0.0-cp313-cp313-win_amd64.whl (27.3 MB)
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   - -------------------------------------- 0.8/27.3 MB 17.8 MB/s eta 0:00:02
   ---------------------- ----------------- 15.5/27.3 MB 64.1 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.3 MB 70.3 MB/s eta 0:00:01
   ---------------------------------------- 27.3/27.3 MB 60.3 MB/s  0:00:00
Installing collected packages: pyarrow
Successfully installed pyarrow-24.0.0

In [4]:
# импорт библиотеки polars
import polars as pl

### <font color='forestgreen'>2. Загрузка данных в Polars DataFrame</font>

##### <font color='forestgreen'>2.1. Из CSV</font>

<b>pl.read_csv(path: str)</b>

<i>Параметры:</i>
- path (str): Путь к CSV-файлу.

In [6]:
df = pl.read_csv('data.csv')
df

shape: (13, 8)
┌─────┬─────────┬───────┬────────┬──────────────┬─────────────┬──────────────┬────────┐
│ ID  ┆ Name    ┆ Age   ┆ Gender ┆ Salary       ┆ Department  ┆ Joining_Date ┆ Rating │
│ --- ┆ ---     ┆ ---   ┆ ---    ┆ ---          ┆ ---         ┆ ---          ┆ ---    │
│ i64 ┆ str     ┆ f64   ┆ str    ┆ f64          ┆ str         ┆ str          ┆ f64    │
╞═════╪═════════╪═══════╪════════╪══════════════╪═════════════╪══════════════╪════════╡
│ 1   ┆ John    ┆ 25.0  ┆ Male   ┆ 50000.0      ┆ HR          ┆ 2020-01-01   ┆ 4.5    │
│ 2   ┆ Jane    ┆ 30.0  ┆ Female ┆ 60000.0      ┆ Engineering ┆ 2019-05-15   ┆ 4.2    │
│ 3   ┆ Alice   ┆ null  ┆ Female ┆ 55000.0      ┆ Sales       ┆ 2021-03-20   ┆ 3.8    │
│ 4   ┆ Bob     ┆ 22.0  ┆ Male   ┆ 52000.0      ┆ Engineering ┆ 2018-07-10   ┆ 4.0    │
│ 5   ┆ Charlie ┆ 35.0  ┆ Male   ┆ 70000.0      ┆ HR          ┆ 2017-02-28   ┆ 4.7    │
│ …   ┆ …       ┆ …     ┆ …      ┆ …            ┆ …           ┆ …            ┆ …      │
│ 9   ┆ Grace   ┆ 50.0  ┆ Female ┆ 81333.333333 ┆ Sales       ┆ 2020-04-25   ┆ 4.6    │
│ 10  ┆ Henry   ┆ 110.0 ┆ Male   ┆ 200000.0     ┆ Engineering ┆ 2016-09-30   ┆ 5.0    │
│ 1   ┆ John    ┆ 25.0  ┆ Male   ┆ 50000.0      ┆ HR          ┆ 2020-01-01   ┆ 4.5    │
│ 2   ┆ Jane    ┆ 30.0  ┆ Female ┆ 60000.0      ┆ Engineering ┆ 2019-05-15   ┆ 4.2    │
│ 3   ┆ Alice   ┆ null  ┆ Female ┆ 55000.0      ┆ Sales       ┆ 2021-03-20   ┆ 3.8    │
└─────┴─────────┴───────┴────────┴──────────────┴─────────────┴──────────────┴────────┘

##### <font color='forestgreen'>2.2. Из Pandas DataFrame</font>

<b>pl.from_pandas(df: pd.DataFrame)</b>

<i>Параметры:</i>
- df(pd.DataFrame): Объект Pandas DataFrame.

In [7]:
import pandas as pd
df_pandas = pd.read_csv('data.csv')
df_polars = pl.from_pandas(df_pandas)
df_polars
df_pandas[['Name', 'Age']]

       Name    Age
0      John   25.0
1      Jane   30.0
2     Alice    NaN
3       Bob   22.0
4   Charlie   35.0
5     David   40.0
6      Emma   28.0
7     Frank   45.0
8     Grace   50.0
9     Henry  110.0
10     John   25.0
11     Jane   30.0
12    Alice    NaN

##### <font color='forestgreen'>2.3. Из JSON</font>

<b>pl.read_json(path: str)</b>

<i>Параметры:</i>
- path (str): Путь к файлу JSON.

In [8]:
df = pl.read_json('weather.json')
df

shape: (2, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬──────────┬────────────┬──────────────┬─────────┐
│ date       ┆ temp_min ┆ temp_max ┆ temp_avg ┆ … ┆ pressure ┆ wind_speed ┆ wind_directi ┆ rain_mm │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---        ┆ on           ┆ ---     │
│ str        ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i64      ┆ f64        ┆ ---          ┆ f64     │
│            ┆          ┆          ┆          ┆   ┆          ┆            ┆ i64          ┆         │
╞════════════╪══════════╪══════════╪══════════╪═══╪══════════╪════════════╪══════════════╪═════════╡
│ 2025-09-01 ┆ 13.0     ┆ 27.2     ┆ 20.1     ┆ … ┆ 1015     ┆ 4.5        ┆ 230          ┆ 2.3     │
│ 2025-09-02 ┆ 17.1     ┆ 20.2     ┆ 18.7     ┆ … ┆ 1013     ┆ 5.0        ┆ 245          ┆ 4.7     │
└────────────┴──────────┴──────────┴──────────┴───┴──────────┴────────────┴──────────────┴─────────┘

### <font color='forestgreen'>3. Создание DataFrame в Polars</font>

##### <font color='forestgreen'>3.1. Из словаря</font>

In [9]:
data = {
    'A': [1, 2, 3],
    'B': ['foo', 'bar', 'baz'],
    'C': [True, False, True]
}
df = pl.DataFrame(data)
df

shape: (3, 3)
┌─────┬─────┬───────┐
│ A   ┆ B   ┆ C     │
│ --- ┆ --- ┆ ---   │
│ i64 ┆ str ┆ bool  │
╞═════╪═════╪═══════╡
│ 1   ┆ foo ┆ true  │
│ 2   ┆ bar ┆ false │
│ 3   ┆ baz ┆ true  │
└─────┴─────┴───────┘

##### <font color='forestgreen'>3.2. Из кортежей</font>

In [10]:
data = [
    (1, 'foo', True),
    (2, 'bar', False),
    (3, 'baz', True)
]
df = pl.DataFrame(data, schema=['A', 'B', 'C'], orient = 'row')
df

shape: (3, 3)
┌─────┬─────┬───────┐
│ A   ┆ B   ┆ C     │
│ --- ┆ --- ┆ ---   │
│ i64 ┆ str ┆ bool  │
╞═════╪═════╪═══════╡
│ 1   ┆ foo ┆ true  │
│ 2   ┆ bar ┆ false │
│ 3   ┆ baz ┆ true  │
└─────┴─────┴───────┘

### <font color='forestgreen'>4. Пример создания DataFrame</font>

In [25]:
import numpy as np

strings_data = ["apple", "banana", "cherry", "watermelon", "elderberry"]
integers_data = np.random.randint(1, 100, size = 5)
floats_data = np.random.rand(5)

df = pl.DataFrame({
    "fruit": strings_data,
    "quantity": integers_data,
    "price": floats_data
})

df

shape: (5, 3)
┌────────────┬──────────┬──────────┐
│ fruit      ┆ quantity ┆ price    │
│ ---        ┆ ---      ┆ ---      │
│ str        ┆ i32      ┆ f64      │
╞════════════╪══════════╪══════════╡
│ apple      ┆ 57       ┆ 0.075409 │
│ banana     ┆ 73       ┆ 0.551607 │
│ cherry     ┆ 95       ┆ 0.554445 │
│ watermelon ┆ 2        ┆ 0.055394 │
│ elderberry ┆ 18       ┆ 0.95415  │
└────────────┴──────────┴──────────┘

In [12]:
df.dtypes

[String, Int32, Float64]

In [13]:
df.schema

Schema([('fruit', String), ('quantity', Int32), ('price', Float64)])

In [14]:
df.describe()

shape: (9, 4)
┌────────────┬────────────┬───────────┬──────────┐
│ statistic  ┆ fruit      ┆ quantity  ┆ price    │
│ ---        ┆ ---        ┆ ---       ┆ ---      │
│ str        ┆ str        ┆ f64       ┆ f64      │
╞════════════╪════════════╪═══════════╪══════════╡
│ count      ┆ 5          ┆ 5.0       ┆ 5.0      │
│ null_count ┆ 0          ┆ 0.0       ┆ 0.0      │
│ mean       ┆ null       ┆ 56.6      ┆ 0.450029 │
│ std        ┆ null       ┆ 26.595112 ┆ 0.375167 │
│ min        ┆ apple      ┆ 27.0      ┆ 0.041696 │
│ 25%        ┆ null       ┆ 36.0      ┆ 0.117901 │
│ 50%        ┆ null       ┆ 54.0      ┆ 0.435098 │
│ 75%        ┆ null       ┆ 75.0      ┆ 0.813189 │
│ max        ┆ watermelon ┆ 91.0      ┆ 0.842263 │
└────────────┴────────────┴───────────┴──────────┘

### <font color='forestgreen'>5. Контексты и выражения в polars</font>

<b>Выражения</b> относятся к вычислениям или преобразованиям, которые выполняются над столбцами данных, и позволяют применять различные операции над данными для получения новых результатов. Выражения включают математические операции, агрегирование, сравнение, манипуляции со строками и многое другое.

<b>Контекст</b> - это фундаментальное действие, которое вы хотите выполнить над данными.
- <i>Выбор</i>: Выбор столбцов из фрейма данных
- <i>Фильтрация</i>: Уменьшение размера кадра данных путем извлечения строк, удовлетворяющих заданным условиям.
- <i>Группировка/агрегация</i>: Вычисление сводной статистики в подгруппах данных

### <font color='forestgreen'>6. Выбор и фильтрация данных в Polars</font>

##### <font color='forestgreen'>6.1. Индексация</font>

In [15]:
# Вывод первой строки
df[0]

shape: (1, 3)
┌───────┬──────────┬──────────┐
│ fruit ┆ quantity ┆ price    │
│ ---   ┆ ---      ┆ ---      │
│ str   ┆ i32      ┆ f64      │
╞═══════╪══════════╪══════════╡
│ apple ┆ 91       ┆ 0.842263 │
└───────┴──────────┴──────────┘

In [16]:
# Вывод столбцов fruit и price
df[:,['fruit', "price"]]

shape: (5, 2)
┌────────────┬──────────┐
│ fruit      ┆ price    │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ apple      ┆ 0.842263 │
│ banana     ┆ 0.117901 │
│ cherry     ┆ 0.813189 │
│ watermelon ┆ 0.041696 │
│ elderberry ┆ 0.435098 │
└────────────┴──────────┘

##### <font color='forestgreen'>6.2. Фильтрация</font>

In [17]:
# filter оставляет только строки, удовлетворяющие условию.
df.filter(df["price"] > 0.3) # df.filter(pl.col('price') > 0.3)

shape: (3, 3)
┌────────────┬──────────┬──────────┐
│ fruit      ┆ quantity ┆ price    │
│ ---        ┆ ---      ┆ ---      │
│ str        ┆ i32      ┆ f64      │
╞════════════╪══════════╪══════════╡
│ apple      ┆ 91       ┆ 0.842263 │
│ cherry     ┆ 27       ┆ 0.813189 │
│ elderberry ┆ 54       ┆ 0.435098 │
└────────────┴──────────┴──────────┘

##### <font color='forestgreen'>6.3. Выбор</font>

In [18]:
# Метод select
# select выбирает столбцы или вычисляет выражения, но не фильтрует строки по умолчанию.
df.select(['fruit', 'price'])
# df['fruit', 'price']

shape: (5, 2)
┌────────────┬──────────┐
│ fruit      ┆ price    │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ apple      ┆ 0.842263 │
│ banana     ┆ 0.117901 │
│ cherry     ┆ 0.813189 │
│ watermelon ┆ 0.041696 │
│ elderberry ┆ 0.435098 │
└────────────┴──────────┘

In [19]:
# Метод with_columns
df_1 = df.with_columns([ #Этот метод добавляет новые столбцы в DataFrame
    (pl.col("price") * pl.col("quantity")).alias("total")
])
df_1

shape: (5, 4)
┌────────────┬──────────┬──────────┬───────────┐
│ fruit      ┆ quantity ┆ price    ┆ total     │
│ ---        ┆ ---      ┆ ---      ┆ ---       │
│ str        ┆ i32      ┆ f64      ┆ f64       │
╞════════════╪══════════╪══════════╪═══════════╡
│ apple      ┆ 91       ┆ 0.842263 ┆ 76.64593  │
│ banana     ┆ 36       ┆ 0.117901 ┆ 4.244445  │
│ cherry     ┆ 27       ┆ 0.813189 ┆ 21.956108 │
│ watermelon ┆ 75       ┆ 0.041696 ┆ 3.127185  │
│ elderberry ┆ 54       ┆ 0.435098 ┆ 23.495291 │
└────────────┴──────────┴──────────┴───────────┘

Основное отличие методов select и with_columns заключается в том, что последний не отбрасывает все столбцы DataFrame, а позволяет создать и добавить к ним новый столбец для анализа.

In [20]:
df_2 = df.select([pl.col('fruit'), pl.col('price') * pl.col('quantity')])
df_2

shape: (5, 2)
┌────────────┬───────────┐
│ fruit      ┆ price     │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ apple      ┆ 76.64593  │
│ banana     ┆ 4.244445  │
│ cherry     ┆ 21.956108 │
│ watermelon ┆ 3.127185  │
│ elderberry ┆ 23.495291 │
└────────────┴───────────┘

### <font color='coral'>7. Задача</font>

In [27]:
# Загрузка данных
# Используя Polars, прочитать файл sales.json в DataFrame df_sales
df_sales = pl.read_json('sales.json')
df_sales

shape: (10, 6)
┌──────────┬──────────┬──────────────┬────────┬──────────┬────────────┐
│ order_id ┆ customer ┆ item         ┆ price  ┆ quantity ┆ date       │
│ ---      ┆ ---      ┆ ---          ┆ ---    ┆ ---      ┆ ---        │
│ i64      ┆ str      ┆ str          ┆ f64    ┆ i64      ┆ str        │
╞══════════╪══════════╪══════════════╪════════╪══════════╪════════════╡
│ 1        ┆ Alice    ┆ Laptop       ┆ 1200.0 ┆ 1        ┆ 2025-09-01 │
│ 2        ┆ Bob      ┆ Mouse        ┆ 25.5   ┆ 2        ┆ 2025-09-01 │
│ 3        ┆ Alice    ┆ Keyboard     ┆ 45.0   ┆ 1        ┆ 2025-09-02 │
│ 4        ┆ Charlie  ┆ Monitor      ┆ 300.0  ┆ 1        ┆ 2025-09-02 │
│ 5        ┆ Bob      ┆ Laptop Stand ┆ 60.0   ┆ 1        ┆ 2025-09-03 │
│ 6        ┆ Alice    ┆ USB Cable    ┆ 10.0   ┆ 3        ┆ 2025-09-03 │
│ 7        ┆ Charlie  ┆ Webcam       ┆ 80.0   ┆ 1        ┆ 2025-09-04 │
│ 8        ┆ Bob      ┆ Headphones   ┆ 150.0  ┆ 1        ┆ 2025-09-04 │
│ 9        ┆ Alice    ┆ Mouse Pad    ┆ 12.0   ┆ 2        ┆ 2025-09-05 │
│ 10       ┆ Charlie  ┆ Keyboard     ┆ 45.0   ┆ 1        ┆ 2025-09-05 │
└──────────┴──────────┴──────────────┴────────┴──────────┴────────────┘

In [28]:
# Фильтрация данных
# Оставить только продажи, где price > 50.
# Отфильтрованный dataframe назовите df_sales_filtered
df_sales_filtered = df_sales.filter(pl.col('price') > 50)
df_sales_filtered

shape: (5, 6)
┌──────────┬──────────┬──────────────┬────────┬──────────┬────────────┐
│ order_id ┆ customer ┆ item         ┆ price  ┆ quantity ┆ date       │
│ ---      ┆ ---      ┆ ---          ┆ ---    ┆ ---      ┆ ---        │
│ i64      ┆ str      ┆ str          ┆ f64    ┆ i64      ┆ str        │
╞══════════╪══════════╪══════════════╪════════╪══════════╪════════════╡
│ 1        ┆ Alice    ┆ Laptop       ┆ 1200.0 ┆ 1        ┆ 2025-09-01 │
│ 4        ┆ Charlie  ┆ Monitor      ┆ 300.0  ┆ 1        ┆ 2025-09-02 │
│ 5        ┆ Bob      ┆ Laptop Stand ┆ 60.0   ┆ 1        ┆ 2025-09-03 │
│ 7        ┆ Charlie  ┆ Webcam       ┆ 80.0   ┆ 1        ┆ 2025-09-04 │
│ 8        ┆ Bob      ┆ Headphones   ┆ 150.0  ┆ 1        ┆ 2025-09-04 │
└──────────┴──────────┴──────────────┴────────┴──────────┴────────────┘

In [29]:
# Выбор колонок
# Создать новый DataFrame df_sales_selected, оставив только колонки: item, price, quantity.
df_sales_selected = df_sales.select(['item', 'price', 'quantity'])
df_sales_selected

shape: (10, 3)
┌──────────────┬────────┬──────────┐
│ item         ┆ price  ┆ quantity │
│ ---          ┆ ---    ┆ ---      │
│ str          ┆ f64    ┆ i64      │
╞══════════════╪════════╪══════════╡
│ Laptop       ┆ 1200.0 ┆ 1        │
│ Mouse        ┆ 25.5   ┆ 2        │
│ Keyboard     ┆ 45.0   ┆ 1        │
│ Monitor      ┆ 300.0  ┆ 1        │
│ Laptop Stand ┆ 60.0   ┆ 1        │
│ USB Cable    ┆ 10.0   ┆ 3        │
│ Webcam       ┆ 80.0   ┆ 1        │
│ Headphones   ┆ 150.0  ┆ 1        │
│ Mouse Pad    ┆ 12.0   ┆ 2        │
│ Keyboard     ┆ 45.0   ┆ 1        │
└──────────────┴────────┴──────────┘

In [30]:
# Добавление новой колонки
# С помощью with_columns добавить колонку total_value, которая равна price * quantity.
# Получившийся DataFrame назовите df_sales_final
df_sales_final = df_sales.with_columns(
    (pl.col('price') * pl.col('quantity')).alias('total_value')
)
df_sales_final

shape: (10, 7)
┌──────────┬──────────┬──────────────┬────────┬──────────┬────────────┬─────────────┐
│ order_id ┆ customer ┆ item         ┆ price  ┆ quantity ┆ date       ┆ total_value │
│ ---      ┆ ---      ┆ ---          ┆ ---    ┆ ---      ┆ ---        ┆ ---         │
│ i64      ┆ str      ┆ str          ┆ f64    ┆ i64      ┆ str        ┆ f64         │
╞══════════╪══════════╪══════════════╪════════╪══════════╪════════════╪═════════════╡
│ 1        ┆ Alice    ┆ Laptop       ┆ 1200.0 ┆ 1        ┆ 2025-09-01 ┆ 1200.0      │
│ 2        ┆ Bob      ┆ Mouse        ┆ 25.5   ┆ 2        ┆ 2025-09-01 ┆ 51.0        │
│ 3        ┆ Alice    ┆ Keyboard     ┆ 45.0   ┆ 1        ┆ 2025-09-02 ┆ 45.0        │
│ 4        ┆ Charlie  ┆ Monitor      ┆ 300.0  ┆ 1        ┆ 2025-09-02 ┆ 300.0       │
│ 5        ┆ Bob      ┆ Laptop Stand ┆ 60.0   ┆ 1        ┆ 2025-09-03 ┆ 60.0        │
│ 6        ┆ Alice    ┆ USB Cable    ┆ 10.0   ┆ 3        ┆ 2025-09-03 ┆ 30.0        │
│ 7        ┆ Charlie  ┆ Webcam       ┆ 80.0   ┆ 1        ┆ 2025-09-04 ┆ 80.0        │
│ 8        ┆ Bob      ┆ Headphones   ┆ 150.0  ┆ 1        ┆ 2025-09-04 ┆ 150.0       │
│ 9        ┆ Alice    ┆ Mouse Pad    ┆ 12.0   ┆ 2        ┆ 2025-09-05 ┆ 24.0        │
│ 10       ┆ Charlie  ┆ Keyboard     ┆ 45.0   ┆ 1        ┆ 2025-09-05 ┆ 45.0        │
└──────────┴──────────┴──────────────┴────────┴──────────┴────────────┴─────────────┘