# <b><font color='lightcoral'>Summary</font></b>

In [1]:
# Подключение библиотеки
import pandas as pd
import numpy as np

<font color='lightcoral'>Ключевые структуры данных:</font>
- <b>DataFrame</b> - двумерная структура данных (таблица)
- <b>Series</b> - одномерный массив данных

<font color='lightcoral'>Создание Series и DataFrame:</font>

In [2]:
# Создание Series
# Из массива
arr = np.array([1, 3, 5, np.nan, 6, 8])
series_from_arr = pd.Series(arr)

# Из списка
series_from_list = pd.Series([12,5,7,9])

# Из словаря
series_from_dict = pd.Series({'a':1, 'b':2, 'c':3})

# Из DataFrame
# ser_from_df = pd.Series(df_from_file['Name'])

In [3]:
# Создание DataFrame
# Из массива
arr_for_df = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_from_array = pd.DataFrame(arr_for_df, columns = ['a', 'b', 'c'])

# Из словаря
dict_for_df = {'col1': [1, 2], 'col2': ['a', 'b']}
df_from_dict = pd.DataFrame(dict_for_df)

# Из словаря с использованием объекта Series
dict_for_df = {'col2': pd.Series([5, 6], index = [0, 1]),'col1': [0, 1, 2, 3], }
df_from_dict = pd.DataFrame(dict_for_df, index=[0, 1, 2, 3])

# Из нескольких Series
ser_1 = pd.Series([1, 2, 3, 4])
ser_2 = pd.Series(['a', 'b', 'c', 'd'])
df_from_series = pd.DataFrame(pd.concat([ser_1, ser_2], axis = 1))

# Из файла
df_from_file = pd.read_csv('titanic.csv')
df_from_file

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

<font color='lightcoral'>Индексация</font>

In [4]:
# Series
ser = pd.Series([1, 3, 5, np.nan, 6, 8])
print(ser)
# Элемент с индексом 2
print(ser[2])

#Срез элементов с индексами от 2 до 4 включительно
print(ser[2:5])

# По метке (имени индекса)
series_str = pd.Series([10, 20, 30, 40, 50], index = ['Store_1', 'Store_2', 'Store_3', 'Store_4', 'Store_5'])
print(series_str)
print(series_str['Store_3'])

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
5.0
2    5.0
3    NaN
4    6.0
dtype: float64
Store_1    10
Store_2    20
Store_3    30
Store_4    40
Store_5    50
dtype: int64
30

In [5]:
# DataFrame
df_from_file = pd.read_csv('titanic.csv')
print(df_from_file.head(5))
print('-----------------------')
# Столбец с названием Age
print(df_from_file.Age)
print(df_from_file['Age'])
print('-----------------------')
#Выбор нескольких столбцов
print(df_from_file[['Name', 'Age', 'Sex']])
print('-----------------------')
# Получение элемента массива. Сначала надо указать столбец, потом строку 
print(df_from_file['Name'][5])
print('-----------------------')
#Получение среза
print(df_from_file[10:20]) #правая граница не включается
print('-----------------------')
#Вывод с шагом
print(df_from_file[1:30:2])

df_from_file[2:3]

   Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2         1       3                              Miss. Laina Heikkinen
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
4         0       3                            Mr. William Henry Allen

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0    male  22.0                        1                        0   7.2500
1  female  38.0                        1                        0  71.2833
2  female  26.0                        0                        0   7.9250
3  female  35.0                        1                        0  53.1000
4    male  35.0                        0                        0   8.0500
-----------------------
0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
882    27.0
883    19.0
884     7.0
885    26.0
886    32.0
Name: Age, Length: 887, dtype: float64
0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
882    27.0
883    19.0
884     7.0
885    26.0
886    32.0
Name: Age, Length: 887, dtype: float64
-----------------------
                                                  Name   Age     Sex
0                               Mr. Owen Harris Braund  22.0    male
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0  female
2                                Miss. Laina Heikkinen  26.0  female
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  35.0  female
4                              Mr. William Henry Allen  35.0    male
..                                                 ...   ...     ...
882                               Rev. Juozas Montvila  27.0    male
883                        Miss. Margaret Edith Graham  19.0  female
884                     Miss. Catherine Helen Johnston   7.0  female
885                               Mr. Karl Howell Behr  26.0    male
886                                 Mr. Patrick Dooley  32.0    male

[887 rows x 3 columns]
-----------------------
Mr. James Moran
-----------------------
    Survived  Pclass                                               Name  \
10         1       3                     Miss. Marguerite Rut Sandstrom
11         1       1                            Miss. Elizabeth Bonnell
12         0       3                      Mr. William Henry Saundercock
13         0       3                         Mr. Anders Johan Andersson
14         0       3                Miss. Hulda Amanda Adolfina Vestrom
15         1       2                     Mrs. (Mary D Kingcome) Hewlett
16         0       3                                Master. Eugene Rice
17         1       2                        Mr. Charles Eugene Williams
18         0       3  Mrs. Julius (Emelia Maria Vandemoortele) Vande...
19         1       3                             Mrs. Fatima Masselmani

       Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
10  female   4.0                        1                        1  16.7000
11  female  58.0                        0                        0  26.5500
12    male  20.0                        0                        0   8.0500
13    male  39.0                        1                        5  31.2750
14  female  14.0                        0                        0   7.8542
15  female  55.0                        0                        0  16.0000
16    male   2.0                        4                        1  29.1250
17    male  23.0                        0                        0  13.0000
18  female  31.0                        1                        0  18.0000
19  female  22.0                        0                        0   7.2250
-----------------------
    Survived  Pclass                                               Name  \
1          1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
3          1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
5          0       3                                    Mr. James Moran
7          0       3                      Master. Gosta Leonard Palsson
9          1       2                 Mrs. Nicholas (Adele Achem) Nasser
11         1       1                            Miss. Elizabeth Bonnell
13         0       3                         Mr. Anders Johan Andersson
15         1       2                     Mrs. (Mary D Kingcome) Hewlett
17         1       2                        Mr. Charles Eugene Williams
19         1       3                             Mrs. Fatima Masselmani
21         1       2                               Mr. Lawrence Beesley
23         1       1                        Mr. William Thompson Sloper
25         1       3  Mrs. Carl Oscar (Selma Augusta Emilia Johansso...
27         0       1                      Mr. Charles Alexander Fortune
29         0       3                                 Mr. Lalio Todoroff

       Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard      Fare
1   female  38.0                        1                        0   71.2833
3   female  35.0                        1                        0   53.1000
5     male  27.0                        0                        0    8.4583
7     male   2.0                        3                        1   21.0750
9   female  14.0                        1                        0   30.0708
11  female  58.0                        0                        0   26.5500
13    male  39.0                        1                        5   31.2750
15  female  55.0                        0                        0   16.0000
17    male  23.0                        0                        0   13.0000
19  female  22.0                        0                        0    7.2250
21    male  34.0                        0                        0   13.0000
23    male  28.0                        0                        0   35.5000
25  female  38.0                        1                        5   31.3875
27    male  19.0                        3                        2  263.0000
29    male  23.0                        0                        0    7.8958

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.925

In [6]:
# loc
# loc - по меткам (названиям)
d = {'one': pd.Series(range(6), index=list('abdefg')),
     'two': pd.Series(range(7), index=list('abcdefg')),
     'three': pd.Series(np.random.normal(size=7), index=list('abcdefg'))}
df = pd.DataFrame(d)
print(df)
print('-----------------------')
# Строка с меткой b
print(df.loc['b'])
print('-----------------------')
# Ячейка на пересечении строки b и столбца one
print(df.loc['b']['one']) # = df['one'][5]
print('-----------------------')
# Ячейки на пересечении строк a, b и столбца one
print(df.loc['a':'b', 'one'])
print('-----------------------')
# Строки a, b и все столбцы
print(df.loc['a':'b', :])
print('-----------------------')
# Все строки и столбец one
print(df.loc[:, 'one'])

   one  two     three
a  0.0    0  0.333364
b  1.0    1 -1.334996
c  NaN    2 -0.961783
d  2.0    3 -0.361010
e  3.0    4 -1.128180
f  4.0    5  2.523025
g  5.0    6  1.944135
-----------------------
one      1.000000
two      1.000000
three   -1.334996
Name: b, dtype: float64
-----------------------
1.0
-----------------------
a    0.0
b    1.0
Name: one, dtype: float64
-----------------------
   one  two     three
a  0.0    0  0.333364
b  1.0    1 -1.334996
-----------------------
a    0.0
b    1.0
c    NaN
d    2.0
e    3.0
f    4.0
g    5.0
Name: one, dtype: float64

In [7]:
# iloc
# iloc - по индексам
d = {'one': pd.Series(range(6), index=list('abdefg')),
     'two': pd.Series(range(7), index=list('abcdefg')),
     'three': pd.Series(np.random.normal(size=7), index=list('abcdefg'))}
df = pd.DataFrame(d)
print(df)
print('-----------------------')
# Строка с индексом 2
print(df.iloc[2])
print('-----------------------')
# Строки с индексами 1 и 2
print(df.iloc[1:3])
print('-----------------------')
# Ячейки на пересечении строк с 1 по 2 и столбцов с 0 по 1
print(df.iloc[1:3, 0:2])

   one  two     three
a  0.0    0  0.734748
b  1.0    1  2.737760
c  NaN    2 -0.145336
d  2.0    3  0.382336
e  3.0    4 -0.758916
f  4.0    5 -0.522271
g  5.0    6  1.085259
-----------------------
one           NaN
two      2.000000
three   -0.145336
Name: c, dtype: float64
-----------------------
   one  two     three
b  1.0    1  2.737760
c  NaN    2 -0.145336
-----------------------
   one  two
b  1.0    1
c  NaN    2

In [8]:
#Булевская индексация = фильтрация
# По столбцу Age выбираем значения больше 70
print(df_from_file[df_from_file.Age > 70])
# По столбцу Age выбираем значения больше 30 и по столбцу Sex значение male
print(df_from_file[(df_from_file.Age > 30) & (df_from_file.Sex == 'male')])

     Survived  Pclass                                 Name   Sex   Age  \
95          0       1             Mr. George B Goldschmidt  male  71.0
115         0       3                  Mr. Patrick Connors  male  70.5
490         0       1               Mr. Ramon Artagaveytia  male  71.0
627         1       1  Mr. Algernon Henry Wilson Barkworth  male  80.0
847         0       3                   Mr. Johan Svensson  male  74.0

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare
95                         0                        0  34.6542
115                        0                        0   7.7500
490                        0                        0  49.5042
627                        0                        0  30.0000
847                        0                        0   7.7750
     Survived  Pclass                                 Name   Sex   Age  \
4           0       3              Mr. William Henry Allen  male  35.0
6           0       1               Mr. Timothy J McCarthy  male  54.0
13          0       3           Mr. Anders Johan Andersson  male  39.0
20          0       2                  Mr. Joseph J Fynney  male  35.0
21          1       2                 Mr. Lawrence Beesley  male  34.0
..        ...     ...                                  ...   ...   ...
863         0       1  Mr. Washington Augustus II Roebling  male  31.0
868         0       1              Mr. Frans Olof Carlsson  male  33.0
869         0       3           Mr. Victor Vander Cruyssen  male  47.0
877         0       3                    Mr. Johann Markun  male  33.0
886         0       3                   Mr. Patrick Dooley  male  32.0

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare
4                          0                        0   8.0500
6                          0                        0  51.8625
13                         1                        5  31.2750
20                         0                        0  26.0000
21                         0                        0  13.0000
..                       ...                      ...      ...
863                        0                        0  50.4958
868                        0                        0   5.0000
869                        0                        0   9.0000
877                        0                        0   7.8958
886                        0                        0   7.7500

[240 rows x 8 columns]

In [9]:
# Фильтрация по маске
# LIKE "%text%"
print(df_from_file[df_from_file['Name'].str.contains('John')])
# LIKE "text%"
print(df_from_file[df_from_file['Name'].str.startswith('Mrs.')])
# LIKE "%text"
df_from_file[df_from_file['Name'].str.endswith('Potter')]

     Survived  Pclass                                               Name  \
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
8           1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
41          0       2  Mrs. William John Robert (Dorothy Ann Wonnacot...
44          0       3                            Mr. William John Rogers
97          1       2                Mrs. John T (Ada Julia Bone) Doling
111         0       3                              Mr. David John Barton
116         0       2                     Mr. William John Robert Turpin
159         0       3                            Mr. John Hatfield Cribb
161         0       3                          Mr. John Viktor Bengtsson
164         1       3               Master. Frank John William Goldsmith
167         0       1                                 Mr. John D Baumann
171         1       3                        Miss. Eleanor Ileen Johnson
187         0       3                                    Mr. John Bourke
211         0       3                              Mr. John Henry Perkin
225         1       2                           Mr. William John Mellors
226         0       3                               Mr. John Hall Lovell
300         0       3                     Mr. William Cahoone Jr Johnson
322         0       3                            Mr. George John Jr Sage
326         1       3      Mrs. Frank John (Emily Alice Brown) Goldsmith
399         0       3                                     Mr. John Adams
416         0       2                          Mr. William John Matthews
464         0       1                          Mr. John Montgomery Smart
524         0       1                                  Mr. John Farthing
545         0       3                           Mr. Frank John Goldsmith
546         1       2                      Master. John Morgan Jr Davies
547         1       1                         Mr. John Borland Jr Thayer
560         0       3                                   Mr. John Simmons
569         1       1                               Mr. John Irwin Flynn
571         0       3                        Mr. Alfred George John Rush
578         1       1  Mrs. John Borland (Marian Longstreth Morris) T...
580         0       1                                 Mr. John Hugo Ross
583         0       2                             Mr. John Denzil Jarvis
591         0       2                             Mr. John Henry Chapman
594         0       3                                 Mr. Alfred Johnson
610         0       3                                    Mr. John Horgan
621         0       3                               Mr. David John Bowen
654         0       3                       Mrs. John (Catherine) Bourke
691         0       1                                     Col. John Weir
695         0       1                            Mr. John Borland Thayer
697         1       1   Mrs. John Jacob (Madeleine Talmadge Force) Astor
715         0       3                        Mr. Malkolm Joackim Johnson
729         0       2                          Mr. William John Berriman
756         0       3                                  Mr. John Garfirth
761         1       1                Mrs. John C (Anna Andrews) Hogeboom
779         0       3                              Mr. Andrew G Johnston
814         0       3                    Mr. John Fredrik Alexander Holm
818         0       1                     Jonkheer. John George Reuchlin
821         0       3                                     Mr. John Flynn
844         0       2                                   Rev. John Harper
860         0       2                              Mr. John William Gill
865         1       3                     Master. Harold Theodor Johnson
884         0       3                     Miss. Catherine Helen Johnston

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard      Fare
1    female  38.0                        1                        0   71.2833
8    female  27.0                        0                        2   11.1333
41   female  27.0                        1                        0   21.0000
44     male  30.0                        0                        0    8.0500
97   female  34.0                        0                        1   23.0000
111    male  22.0                        0                        0    8.0500
116    male  29.0                        1                        0   21.0000
159    male  44.0                        0                        1   16.1000
161    male  26.0                        0                        0    7.7750
164    male   9.0                        0                        2   20.5250
167    male  60.0                        0                        0   25.9250
171  female   1.0                        1                        1   11.1333
187    male  40.0                        1                        1   15.5000
211    male  22.0                        0                        0    7.2500
225    male  19.0                        0                        0   10.5000
226    male  20.5                        0                        0    7.2500
300    male  19.0                        0                        0    0.0000
322    male  20.0                        8                        2   69.5500
326  female  31.0                        1                        1   20.5250
399    male  26.0                        0                        0    8.0500
416    male  30.0                        0                        0   13.0000
464    male  56.0                        0                        0   26.5500
524    male  49.0                        0                        0  221.7792
545    male  33.0                        1                        1   20.5250
546    male   8.0                        1                        1   36.7500
547    male  17.0                        0                        2  110.8833
560    male  40.0                        0                        0    8.0500
569    male  36.0                        0                        0   26.3875
571    male  16.0                        0                        0    8.0500
578  female  39.0                        1                        1  110.8833
580    male  36.0                        0                        0   40.1250
583    male  47.0                        0                        0   15.0000
591    male  37.0                        1                        0   26.0000
594    male  49.0                        0                        0    0.0000
610    male  22.0                        0                        0    7.7500
621    male  21.0                        0                        0   16.1000
654  female  32.0                        1                        1   15.5000
691    male  60.0                        0                        0   26.5500
695    male  49.0                        1                        1  110.8833
697  female  18.0                        1                        0  227.5250
715    male  33.0                        0                        0    7.7750
729    male  23.0                        0                        0   13.0000
756    male  23.0                        0                        0   14.5000
761  female  51.0                        1                        0   77.9583
779    male  35.0                        1                        2   23.4500
814    male  43.0                        0                        0    6.4500
818    male  38.0                        0                        0    0.0000
821    male  36.0                        0                        0    6.9500
844    male  28.0                        0                        1   33.0000
860    male  24.0                        0                        0   13.0000
865    male   4.0                        1                        1   11.1333
884  female   7.0                        1                        2   23.4500
     Survived  Pclass                                               Name  \
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
8           1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9           1       2                 Mrs. Nicholas (Adele Achem) Nasser
15          1       2                     Mrs. (Mary D Kingcome) Hewlett
..        ...     ...                                                ...
867         1       1    Mrs. Richard Leonard (Sallie Monypeny) Beckwith
870         1       2               Mrs. Samuel (Hannah Wizosky) Abelson
875         1       1       Mrs. Thomas Jr (Lily Alexenia Wilson) Potter
876         1       2        Mrs. William (Imanita Parrish Hall) Shelley
881         0       3                Mrs. William (Margaret Norton) Rice

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
1    female  38.0                        1                        0  71.2833
3    female  35.0                        1                        0  53.1000
8    female  27.0                        0                        2  11.1333
9    female  14.0                        1                        0  30.0708
15   female  55.0                        0                        0  16.0000
..      ...   ...                      ...                      ...      ...
867  female  47.0                        1                        1  52.5542
870  female  28.0                        1                        0  24.0000
875  female  56.0                        0                        1  83.1583
876  female  25.0                        0                        1  26.0000
881  female  39.0                        0                        5  29.1250

[125 rows x 8 columns]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
875,1,1,Mrs. Thomas Jr (Lily Alexenia Wilson) Potter,female,56.0,0,1,83.1583

<font color='lightcoral'>Основные функции</font>

In [10]:
# Статистическое описание 
print(ser.describe())
print(df_from_file.describe())

count    5.000000
mean     4.600000
std      2.701851
min      1.000000
25%      3.000000
50%      5.000000
75%      6.000000
max      8.000000
dtype: float64
         Survived      Pclass         Age  Siblings/Spouses Aboard  \
count  887.000000  887.000000  887.000000               887.000000
mean     0.385569    2.305524   29.471443                 0.525366
std      0.487004    0.836662   14.121908                 1.104669
min      0.000000    1.000000    0.420000                 0.000000
25%      0.000000    2.000000   20.250000                 0.000000
50%      0.000000    3.000000   28.000000                 0.000000
75%      1.000000    3.000000   38.000000                 1.000000
max      1.000000    3.000000   80.000000                 8.000000

       Parents/Children Aboard       Fare
count               887.000000  887.00000
mean                  0.383315   32.30542
std                   0.807466   49.78204
min                   0.000000    0.00000
25%                   0.000000    7.92500
50%                   0.000000   14.45420
75%                   0.000000   31.13750
max                   6.000000  512.32920

In [11]:
# Вычисление разности по строкам
df_from_file['Age'].diff(periods = 2)

0       NaN
1       NaN
2       4.0
3      -3.0
4       9.0
       ...
882     2.0
883   -20.0
884   -20.0
885     7.0
886    25.0
Name: Age, Length: 887, dtype: float64

In [12]:
# Удаление значений с NaN
ser_name = df_from_file.Name.dropna()
ser_name

0                                 Mr. Owen Harris Braund
1      Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                  Miss. Laina Heikkinen
3            Mrs. Jacques Heath (Lily May Peel) Futrelle
4                                Mr. William Henry Allen
                             ...
882                                 Rev. Juozas Montvila
883                          Miss. Margaret Edith Graham
884                       Miss. Catherine Helen Johnston
885                                 Mr. Karl Howell Behr
886                                   Mr. Patrick Dooley
Name: Name, Length: 887, dtype: object

In [13]:
# Заполнение ячеек с NaN
df_from_file.Sex.fillna('male')

0        male
1      female
2      female
3      female
4        male
        ...
882      male
883    female
884    female
885      male
886      male
Name: Sex, Length: 887, dtype: object

<font color='lightcoral'>Подключение к БД</font><br>
Способ №1

In [14]:
# Установка необходимых библиотек
!pip install pandas mysql-connector-python

Requirement already satisfied: pandas in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
    --------------------------------------- 0.3/16.5 MB ? eta -:--:--
   ---------------------- ----------------- 9.4/16.5 MB 43.6 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 47.2 MB/s  0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

In [15]:
# Импорт необходимой библиотеки
import mysql.connector

In [16]:
# Создание соединения
conn = mysql.connector.connect(
    host="YOUR_MYSQL_HOST",
    user="ich1",
    password="password",
    database="sakila"
)

In [17]:
# Чтение данных из таблицы в БД в DataFrame
import pandas as pd
query = "SELECT * FROM sakila.actor"
df = pd.read_sql(query, conn)
df.head()

C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_37716\776634567.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

   actor_id first_name     last_name         last_update
0         1   PENELOPE       GUINESS 2006-02-15 04:34:33
1         2       NICK      WAHLBERG 2006-02-15 04:34:33
2         3         ED         CHASE 2006-02-15 04:34:33
3         4   JENNIFER         DAVIS 2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA 2006-02-15 04:34:33

In [18]:
# Закрытие соединения
conn.close()

<font color='lightcoral'>Подключение к БД</font><br>
Способ №2

In [19]:
# Установка необходимых библиотек
! pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: pymysql in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.1.2)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.4.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.49-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------  2.1/2.1 MB 30.8 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 23.2 MB/s  0:00:00
Downloading greenlet-3.4.0-cp313-cp313-win_amd64.whl (238 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.4.0 sqlalchemy-2.0.49

In [20]:
# Импорт необходимой библиотеки
from sqlalchemy import create_engine

In [21]:
# Создание соединения
engine = create_engine(
    "mysql+pymysql://ich1:password@YOUR_MYSQL_HOST/sakila"
)

In [ ]:
# Чтение данных из таблицы в БД в DataFrame
query = "SELECT * FROM sakila.actor"
df = pd.read_sql(query, engine)
df.head()

   actor_id first_name     last_name         last_update
0         1   PENELOPE       GUINESS 2006-02-15 04:34:33
1         2       NICK      WAHLBERG 2006-02-15 04:34:33
2         3         ED         CHASE 2006-02-15 04:34:33
3         4   JENNIFER         DAVIS 2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA 2006-02-15 04:34:33

<font color='lightcoral'>Решение задач</font>

1. Датасет country_wise_latest.csv содержит последнюю доступную сводку по странам. Основные колонки:
- Country/Region — страна
- Confirmed — общее число подтверждённых случаев
- Deaths — общее число смертей
- Recovered — общее число выздоровевших
- Active — количество активных случаев
- New cases — новые случаи за последний день
- New deaths — новые смерти за последний день
- New recovered — новые выздоровевшие за последний день
- Deaths / 100 Cases — показатель смертности на 100 случаев
- Recovered / 100 Cases — показатель выздоровления на 100 случаев
- Deaths / 100 Recovered — соотношение смертей к выздоровлениям
- Confirmed last week — подтвержденные случаи неделей ранее
- 1 week change — изменение за неделю
- 1 week % increase — процентный прирост за неделю
- WHO Region — регион ВОЗ

1. Загрузите данные в DataFrame.
2. Выведите первые 10 строк и размеры датасета.
3. Получите все данные для страны Italy.
4. Выведите первые 5 строк и первые 4 столбца с помощью .iloc.
5. С помощью .loc выберите колонки "Страна", "Кол-во подтвержденных случаев" и "Общее число выздоровевших" для стран Germany и France.
6. Найдите все страны, где общее число подтверждённых случаев больше 1 млн.
7. Выведите все страны, у которых Количество активных случаев больше 50000 и одновременно общее число выздоровевших более 0,5 млн.
8. Найдите:
- страну с максимальным числом случаев
- среднее число активных случаев по всем странам,
- медианное значение новых случаев.
9. Получите Series, содержащую количество новых выздоровлений по всем странам.
10. Создайте новый DataFrame, в котором будут только колонки:['Country/Region', 'Confirmed', 'Deaths', 'Recovered'].
11. Из него сформируйте DataFrame только для стран: Italy, Spain, France, Germany.
12. Найдите ТОП-5 стран с наибольшим приростом за неделю.

In [52]:
df = pd.read_csv("country_wise_latest.csv")
df

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [ ]:
# 2) Первые 10 строк и размер датасета

display(df.head(10))
print('Размер датасета:', df.shape)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
5,Antigua and Barbuda,86,3,65,18,4,0,5,3.49,75.58,4.62,76,10,13.16,Americas
6,Argentina,167416,3059,72575,91782,4890,120,2057,1.83,43.35,4.21,130774,36642,28.02,Americas
7,Armenia,37390,711,26665,10014,73,6,187,1.90,71.32,2.67,34981,2409,6.89,Europe
8,Australia,15303,167,9311,5825,368,6,137,1.09,60.84,1.79,12428,2875,23.13,Western Pacific
9,Austria,20558,713,18246,1599,86,1,37,3.47,88.75,3.91,19743,815,4.13,Europe

Размер датасета: (187, 15)

In [ ]:
# 3) Все данные по стране Italy
df[df['Country/Region'] == 'Italy']

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
85,Italy,246286,35112,198593,12581,168,5,147,14.26,80.64,17.68,244624,1662,0.68,Europe

In [ ]:
# 4) Первые 5 строк и первые 4 столбца через .iloc
df.iloc[:5, :4]

  Country/Region  Confirmed  Deaths  Recovered
0    Afghanistan      36263    1269      25198
1        Albania       4880     144       2745
2        Algeria      27973    1163      18837
3        Andorra        907      52        803
4         Angola        950      41        242

In [ ]:
# 5) Через .loc выбрать страны Germany и France и колонки
df.loc[
    df['Country/Region'].isin(['Germany', 'France']),
    ['Country/Region', 'Confirmed', 'Recovered']
]

   Country/Region  Confirmed  Recovered
61         France     220352      81212
65        Germany     207112     190314

In [41]:
# 6) Все страны, где подтверждённых случаев больше 1 млн
df[df['Confirmed'] > 1_000_000][['Country/Region', 'Confirmed']]

    Country/Region  Confirmed
23          Brazil    2442375
79           India    1480073
173             US    4290259

In [ ]:
# 7) Активных случаев > 50000 и выздоровевших > 0.5 млн

df[(df['Active'] > 50000) & (df['Recovered'] > 500000)]

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
138,Russia,816680,13334,602249,201097,5607,85,3077,1.63,73.74,2.21,776212,40468,5.21,Europe
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas

In [38]:
# 8) Найти максимум, среднее и медиану
# страна с максимальным числом случаев
max_country = df.loc[df['Confirmed'].idxmax(), 'Country/Region']

# среднее число активных случаев
avg_active = round(df['Active'].mean(),2)

# медианное значение новых случаев
median_new_cases = df['New cases'].median()

print('Страна с максимальным числом случаев:', max_country)
print('Среднее число активных случаев:', avg_active)
print('Медиана новых случаев:', median_new_cases)

Страна с максимальным числом случаев: US
Среднее число активных случаев: 34001.94
Медиана новых случаев: 49.0

In [ ]:
# 9) Series с количеством новых выздоровлений по всем странам
new_recovered_series = df.set_index('Country/Region')['New recovered']
new_recovered_series

Country/Region
Afghanistan            18
Albania                63
Algeria               749
Andorra                 0
Angola                  0
                     ...
West Bank and Gaza      0
Western Sahara          0
Yemen                  36
Zambia                465
Zimbabwe               24
Name: New recovered, Length: 187, dtype: int64

In [ ]:
# 10) Новый DataFrame только с нужными колонками

df_small = df[['Country/Region', 'Confirmed', 'Deaths', 'Recovered']]
df_small

         Country/Region  Confirmed  Deaths  Recovered
0           Afghanistan      36263    1269      25198
1               Albania       4880     144       2745
2               Algeria      27973    1163      18837
3               Andorra        907      52        803
4                Angola        950      41        242
..                  ...        ...     ...        ...
182  West Bank and Gaza      10621      78       3752
183      Western Sahara         10       1          8
184               Yemen       1691     483        833
185              Zambia       4552     140       2815
186            Zimbabwe       2704      36        542

[187 rows x 4 columns]

In [ ]:
# 11) DataFrame только для Italy, Spain, France, Germany
df_europe = df_small[df_small['Country/Region'].isin(['Italy', 'Spain', 'France', 'Germany'])]
df_europe

    Country/Region  Confirmed  Deaths  Recovered
61          France     220352   30212      81212
65         Germany     207112    9125     190314
85           Italy     246286   35112     198593
157          Spain     272421   28432     150376

In [ ]:
# 12) ТОП-5 стран с наибольшим приростом за неделю
df.sort_values(by='1 week change', ascending=False).head(5)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
154,South Africa,452529,7067,274925,170537,7096,298,9848,1.56,60.75,2.57,373628,78901,21.12,Africa
37,Colombia,257101,8777,131161,117163,16306,508,11494,3.41,51.02,6.69,204005,53096,26.03,Americas

In [36]:
df.sort_values(by='1 week % increase', ascending=False).head(5)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
130,Papua New Guinea,62,0,11,51,0,0,0,0.00,17.74,0.00,19,43,226.32,Western Pacific
63,Gambia,326,8,66,252,49,2,6,2.45,20.25,12.12,112,214,191.07,Africa
11,Bahamas,382,11,91,280,40,0,0,2.88,23.82,12.09,174,208,119.54,Americas
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa
99,Libya,2827,64,577,2186,158,4,24,2.26,20.41,11.09,1980,847,42.78,Eastern Mediterranean

In [56]:
df_new_index = df.set_index(['Country/Region'],inplace = True)
# df.reset_index(inplace = True)

In [57]:
new_series = pd.Series(df['New recovered'])
new_series

Country/Region
Afghanistan            18
Albania                63
Algeria               749
Andorra                 0
Angola                  0
                     ...
West Bank and Gaza      0
Western Sahara          0
Yemen                  36
Zambia                465
Zimbabwe               24
Name: New recovered, Length: 187, dtype: int64

In [60]:
print(new_series.loc['Yemen'])

36