# <b><font color='rebeccapurple'>Practicum 13</font></b>

### <font color='rebeccapurple'>1. Описание датасета</font>

Этот набор данных содержит информацию о демографических характеристиках сотрудников, должностях и зарплатах в различных отраслях.

<b> Поля: </b>
- <i> Age </i> - Возраст сотрудника (21 - 62 года)
- <i> Gender </i> - Пол (male/female)
- <i> Education Level </i> - Образование (Bachelor's, Master's, PhD, High School)
- <i> Job Title </i> - наименование/роль сотрудника
- <i> Years of Experience </i> - опыт работы (0 - 34 года)
- <i> Salary </i> - годовая заработная плата сотрудника (350 - 250 000)

### <font color='rebeccapurple'>2. Загрузка данных</font>

In [1]:
# мпортируйте необходимые библиотеки (pandas, plotly.express)
import plotly.express as px
import pandas as pd

In [3]:
# Загрузите датасет Salary_Data.csv в Pandas DataFrame
# Получившийся DataFrame назовите df_salary
df_salary = pd.read_csv('../data/Salary_Data.csv')
df_salary

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

### <font color='rebeccapurple'>3. Очистка и подготовка данных</font>

##### <font color='rebeccapurple'>3.1. Приведение данных к единым названиям</font>

In [9]:
# Выведите уникальные значения для столбца Education Level
df_salary_education_unique = df_salary.groupby('Education Level').size().reset_index(name='Count')
df_salary_education_unique

     Education Level  Count
0         Bachelor's    756
1  Bachelor's Degree   2267
2        High School    448
3           Master's    288
4    Master's Degree   1573
5                PhD   1368
6                phD      1

In [13]:
# Приведите все названия к единому формату
# Должно остаться 4 значения: Bachelor's, Master's, PhD, High School (не считая nan)
# спользуйте метод replace()
df_salary['Education Level'] = df_salary['Education Level'].replace({
    "Bachelor's Degree": "Bachelor's",
    "Master's Degree": "Master's",
    'phD': "PhD",
})
df_salary_education_unique = df_salary.groupby('Education Level').size().reset_index(name='Count')
df_salary_education_unique

  Education Level  Count
0      Bachelor's   3023
1     High School    448
2        Master's   1861
3             PhD   1369

##### <font color='rebeccapurple'>3.2. Обработка пропущенных значений</font>

In [17]:
# Посчитайте общее количество пропущенных значений в каждой строке
df_salary.isnull().sum()

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
dtype: int64

In [55]:
# Выведите строки с пропущенными значениями
df_salary[df_salary.isnull().any(axis=1)]

Empty DataFrame
Columns: [Age, Gender, Education Level, Job Title, Years of Experience, Salary, age_range]
Index: []

In [20]:
# Удалите строки, в которых все значения пропущены
# спользуйте метод dropna с параметрами axis = 0, how = 'all', inplace = True
df_salary.dropna(axis=0, how='all', inplace=True)
df_salary.isnull().sum()

Age                    0
Gender                 0
Education Level        1
Job Title              0
Years of Experience    1
Salary                 3
dtype: int64

In [ ]:
# Указываем, в каких конкретно столбцах необходимо искать
df.dropna(subset=['one','flag'], inplace=True)

##### <font color='rebeccapurple'>3.3. Работа с выбросами</font>

In [23]:
# 1. Отстутсвующие значения в поле Education Level заполните модой по Education Level
# 2. Отстутсвующие значения в поле Years of Experience заполните средним значением по Years of Experience
# 3. Отстутсвующие значения в поле Salary заполните медианой по Salary
df_salary['Education Level'].fillna(df_salary['Education Level'].mode()[0], inplace=True)
df_salary['Years of Experience'].fillna(df_salary['Years of Experience'].mean(), inplace=True)
df_salary['Salary'].fillna(df_salary['Salary'].median(), inplace=True)
df_salary.isnull().sum()

C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_52204\3291337664.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_salary['Years of Experience'].fillna(df_salary['Years of Experience'].mean(), inplace=True)
C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_52204\3291337664.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_salary['Salary'].fillna(df_salary['Salary'].median(), inplace=True)

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [26]:
# зучите выбросы для столбцов Age, Years of Experience и Salary с помощью boxplot
# При наличии выбросов подумайте, как с ними быть
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=3, subplot_titles=['Age', 'Years of Experience', 'Salary'])

fig.add_trace(go.Box(y=df_salary['Age'], name='Age'), row=1, col=1)
fig.add_trace(go.Box(y=df_salary['Years of Experience'], name='Years of Experience'), row=1, col=2)
fig.add_trace(go.Box(y=df_salary['Salary'], name='Salary'), row=1, col=3)

fig.update_layout(title='Boxplots for Age, Years of Experience and Salary', showlegend=False)
fig.show()

In [85]:
df_salary['count'] = 1

df_salary.groupby(['Age','Gender','Education Level', 'Job Title','Years of Experience', 'Salary']).sum()[['count']]\
.reset_index()\
.sort_values('count', ascending=False)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,count
315,27.0,Male,Bachelor's,Software Engineer,3.0,80000.0,45
56,24.0,Female,High School,Receptionist,0.0,25000.0,45
791,32.0,Male,Bachelor's,Product Manager,7.0,120000.0,45
798,32.0,Male,Bachelor's,Software Engineer,8.0,190000.0,39
865,33.0,Female,Master's,Product Manager,11.0,198000.0,38
...,...,...,...,...,...,...,...
1786,60.0,Male,PhD,Software Engineer Manager,18.0,195000.0,1
12,23.0,Female,Bachelor's,Junior Marketing Analyst,0.5,35000.0,1
27,23.0,Male,Bachelor's,Full Stack Engineer,1.0,55000.0,1
29,23.0,Male,Bachelor's,Sales Manager,1.0,35000.0,1
31,23.0,Male,Bachelor's,Software Developer,1.0,45000.0,1

In [81]:
df_salary_1 = df_salary.drop_duplicates()
df_salary_1

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,age_range,Education Level_encode,Job Title_encode,Gender_encode
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0,31 - 40,0,0,0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0,21 - 30,1,1,1
2,45.0,Male,PhD,Senior Manager,15.0,150000.0,41 - 50,2,2,0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0,31 - 40,0,3,1
4,52.0,Male,Master's,Director,20.0,200000.0,51 - 62,1,4,0
...,...,...,...,...,...,...,...,...,...,...
6621,43.0,Female,Master's,Digital Marketing Manager,15.0,150000.0,41 - 50,1,58,1
6622,27.0,Male,High School,Sales Manager,2.0,40000.0,21 - 30,3,7,0
6623,33.0,Female,Bachelor's,Director of Marketing,8.0,80000.0,31 - 40,0,46,1
6626,37.0,Male,Bachelor's,Sales Director,7.0,90000.0,31 - 40,0,19,0
6629,30.0,Female,Bachelor's,Sales Manager,5.0,70000.0,21 - 30,0,7,1

### <font color='rebeccapurple'>4. Распределение данных</font>
[Histogram](https://plotly.com/python-api-reference/generated/plotly.express.histogram.html#plotly.express.histogram)

In [29]:
# С помощью гистограммы изучите распределение данных по Salary
fig = px.histogram(df_salary, x='Salary', title='Distribution of Salary')
fig.update_traces(marker=dict(line=dict(color='black', width=1)))
fig.show()

In [86]:
fig = px.histogram(df_salary_1, x='Salary', title='Distribution of Salary')
fig.update_traces(marker=dict(line=dict(color='black', width=1)))
fig.show()

In [30]:
# С помощью гистограммы изучите распределение данных по Salary в разбивке по полу
# спользуйте параметр facet_col
fig = px.histogram(df_salary, x='Salary', facet_col='Gender', title='Distribution of Salary by  Gender')
fig.update_traces(marker=dict(line=dict(color='black', width=1)))
fig.show()

In [87]:
fig = px.histogram(df_salary_1, x='Salary', facet_col='Gender', title='Distribution of Salary by  Gender')
fig.update_traces(marker=dict(line=dict(color='black', width=1)))
fig.show()

In [31]:
# С помощью гистограммы изучите распределение данных по Salary в разбивке по уровню образования
# спользуйте параметр facet_col
fig = px.histogram(df_salary, x='Salary', facet_col='Education Level', title='Distribution of Salary by Education Level')
fig.update_traces(marker=dict(line=dict(color='black', width=1)))
fig.show()

In [88]:
fig = px.histogram(df_salary_1, x='Salary', facet_col='Education Level', title='Distribution of Salary by Education Level')
fig.update_traces(marker=dict(line=dict(color='black', width=1)))
fig.show()

### <font color='rebeccapurple'>5. Столбчатые диаграммы</font>

In [33]:
# зучите количество людей в каждом уровне образования + в разбивке по возрастным группам:
# - 21 - 30
# - 31 - 40
# - 41 - 50
# - 51 - 62
# 1. Переведите тип DataFrame с Pandas в Polars. DataFrame назовите df_salary_polars
import polars as pl
df_salary_polars = pl.from_pandas(df_salary)
df_salary_polars

shape: (6_702, 6)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ Age  в”† Gender в”† Education Level в”† Job Title             в”† Years of Experience в”† Salary   в”‚
в”‚ ---  в”† ---    в”† ---             в”† ---                   в”† ---                 в”† ---      в”‚
в”‚ f64  в”† str    в”† str             в”† str                   в”† f64                 в”† f64      в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 32.0 в”† Male   в”† Bachelor's      в”† Software Engineer     в”† 5.0                 в”† 90000.0  в”‚
в”‚ 28.0 в”† Female в”† Master's        в”† Data Analyst          в”† 3.0                 в”† 65000.0  в”‚
в”‚ 45.0 в”† Male   в”† PhD             в”† Senior Manager        в”† 15.0                в”† 150000.0 в”‚
в”‚ 36.0 в”† Female в”† Bachelor's      в”† Sales Associate       в”† 7.0                 в”† 60000.0  в”‚
в”‚ 52.0 в”† Male   в”† Master's        в”† Director              в”† 20.0                в”† 200000.0 в”‚
в”‚ вЂ¦    в”† вЂ¦      в”† вЂ¦               в”† вЂ¦                     в”† вЂ¦                   в”† вЂ¦        в”‚
в”‚ 49.0 в”† Female в”† PhD             в”† Director of Marketing в”† 20.0                в”† 200000.0 в”‚
в”‚ 32.0 в”† Male   в”† High School     в”† Sales Associate       в”† 3.0                 в”† 50000.0  в”‚
в”‚ 30.0 в”† Female в”† Bachelor's      в”† Financial Manager     в”† 4.0                 в”† 55000.0  в”‚
в”‚ 46.0 в”† Male   в”† Master's        в”† Marketing Manager     в”† 14.0                в”† 140000.0 в”‚
в”‚ 26.0 в”† Female в”† High School     в”† Sales Executive       в”† 1.0                 в”† 35000.0  в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [35]:
# 2. С помощью условных функций polars добавьте в df_salary_polars столбец age_range
df_salary_polars = df_salary_polars.with_columns(
    pl.when((pl.col('Age') >= 21) & (pl.col('Age') <= 30))
    .then(pl.lit('21 - 30'))
    .when((pl.col('Age') >= 31) & (pl.col('Age') <= 40))
    .then(pl.lit('31 - 40'))
    .when((pl.col('Age') >= 41) & (pl.col('Age') <= 50))
    .then(pl.lit('41 - 50'))
    .when((pl.col('Age') >= 51) & (pl.col('Age') <= 62))
    .then(pl.lit('51 - 62'))
    .otherwise(pl.lit('Unknown'))
    .alias('age_range')
)
df_salary_polars

shape: (6_702, 7)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ Age  в”† Gender в”† Education Level в”† Job Title             в”† Years of   в”† Salary   в”† age_range в”‚
в”‚ ---  в”† ---    в”† ---             в”† ---                   в”† Experience в”† ---      в”† ---       в”‚
в”‚ f64  в”† str    в”† str             в”† str                   в”† ---        в”† f64      в”† str       в”‚
в”‚      в”†        в”†                 в”†                       в”† f64        в”†          в”†           в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 32.0 в”† Male   в”† Bachelor's      в”† Software Engineer     в”† 5.0        в”† 90000.0  в”† 31 - 40   в”‚
в”‚ 28.0 в”† Female в”† Master's        в”† Data Analyst          в”† 3.0        в”† 65000.0  в”† 21 - 30   в”‚
в”‚ 45.0 в”† Male   в”† PhD             в”† Senior Manager        в”† 15.0       в”† 150000.0 в”† 41 - 50   в”‚
в”‚ 36.0 в”† Female в”† Bachelor's      в”† Sales Associate       в”† 7.0        в”† 60000.0  в”† 31 - 40   в”‚
в”‚ 52.0 в”† Male   в”† Master's        в”† Director              в”† 20.0       в”† 200000.0 в”† 51 - 62   в”‚
в”‚ вЂ¦    в”† вЂ¦      в”† вЂ¦               в”† вЂ¦                     в”† вЂ¦          в”† вЂ¦        в”† вЂ¦         в”‚
в”‚ 49.0 в”† Female в”† PhD             в”† Director of Marketing в”† 20.0       в”† 200000.0 в”† 41 - 50   в”‚
в”‚ 32.0 в”† Male   в”† High School     в”† Sales Associate       в”† 3.0        в”† 50000.0  в”† 31 - 40   в”‚
в”‚ 30.0 в”† Female в”† Bachelor's      в”† Financial Manager     в”† 4.0        в”† 55000.0  в”† 21 - 30   в”‚
в”‚ 46.0 в”† Male   в”† Master's        в”† Marketing Manager     в”† 14.0       в”† 140000.0 в”† 41 - 50   в”‚
в”‚ 26.0 в”† Female в”† High School     в”† Sales Executive       в”† 1.0        в”† 35000.0  в”† 21 - 30   в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [99]:
# 3. Переведите датафрейм df_salary_polars из polars в pandas (назовите df_salary)
# спользуйте функцию to_pandas()
df_salary_2 = df_salary_polars.to_pandas()
df_salary_2

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,age_range
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0,31 - 40
1,28.0,Female,Master's,Data Analyst,3.0,65000.0,21 - 30
2,45.0,Male,PhD,Senior Manager,15.0,150000.0,41 - 50
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0,31 - 40
4,52.0,Male,Master's,Director,20.0,200000.0,51 - 62
...,...,...,...,...,...,...,...
6697,49.0,Female,PhD,Director of Marketing,20.0,200000.0,41 - 50
6698,32.0,Male,High School,Sales Associate,3.0,50000.0,31 - 40
6699,30.0,Female,Bachelor's,Financial Manager,4.0,55000.0,21 - 30
6700,46.0,Male,Master's,Marketing Manager,14.0,140000.0,41 - 50
6701,26.0,Female,High School,Sales Executive,1.0,35000.0,21 - 30

In [100]:
# 4. Постройте столбчатую диаграмму (количество людей в каждом уровне образования + в разбивке по возрастным группам)
df_salary_grouped = df_salary_2.groupby(['Education Level', 'age_range']).size().reset_index(name='Count')
fig = px.bar(df_salary_grouped, 
             x='Education Level', 
             y='Count',
             color='age_range', 
             color_discrete_sequence = ['green', 'violet','blue', 'orange'],
             title='Count of People by Education Level and Age Range')
fig.show()

In [104]:
# справьте предыдущий график на анимированный: 
# Должен меняться Age, а каждый столбик - количество человек с определенным уровнем образования
fig = px.bar(df_salary_2, 
             x='Education Level', 
             color='age_range', 
             title='Count of People by Education Level and Age Range',
             animation_frame='Age')
fig.show()

### <font color='rebeccapurple'>6. Круговые диаграммы</font>

In [89]:
# Нарисуйте круговую диаграмму - пончик по полю Gender
fig = px.pie(df_salary, names='Gender', title='Distribution of Gender', hole=0.4, width=600, height=400)
fig.update_traces( # обновить данные объектов
    textinfo = 'value+label')
fig.show()

### <font color='rebeccapurple'>7. Scatter plot</font>

In [53]:
# Нарисуйте scatter-plot по выявлению связи между зарплатой и опытом
# Размер точек должен отображать возрастной ранг сотрудника
# Цвет - уровень образования
fig = px.scatter(df_salary, 
                 x='Years of Experience', 
                 y='Salary',
                 size='Age',
                 color='Education Level',
                 title='Scatter Plot of Salary vs. Years of Experience')
fig.show()

### <font color='rebeccapurple'>8. Heatmap</font>

In [63]:
# Постройте HeatMap для всех параметров, включая категориальные
# 1. Закодируйте категориальные столбцы в числовые с помощью функции factorize
# Получившиеся столбцы назовите Education Level_encode, Job Title_encode, Gender_encode
df_salary.info()
df_salary['Education Level_encode'] = pd.factorize(df_salary['Education Level'])[0]
df_salary['Job Title_encode'] = pd.factorize(df_salary['Job Title'])[0]
df_salary['Gender_encode'] = pd.factorize(df_salary['Gender'])[0]
df_salary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Education Level      6702 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6702 non-null   float64
 5   Salary               6702 non-null   float64
 6   age_range            6702 non-null   object
dtypes: float64(3), object(4)
memory usage: 366.6+ KB

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,age_range,Education Level_encode,Job Title_encode,Gender_encode
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0,31 - 40,0,0,0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0,21 - 30,1,1,1
2,45.0,Male,PhD,Senior Manager,15.0,150000.0,41 - 50,2,2,0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0,31 - 40,0,3,1
4,52.0,Male,Master's,Director,20.0,200000.0,51 - 62,1,4,0
...,...,...,...,...,...,...,...,...,...,...
6697,49.0,Female,PhD,Director of Marketing,20.0,200000.0,41 - 50,2,46,1
6698,32.0,Male,High School,Sales Associate,3.0,50000.0,31 - 40,3,3,0
6699,30.0,Female,Bachelor's,Financial Manager,4.0,55000.0,21 - 30,0,24,1
6700,46.0,Male,Master's,Marketing Manager,14.0,140000.0,41 - 50,1,16,0
6701,26.0,Female,High School,Sales Executive,1.0,35000.0,21 - 30,3,38,1

In [80]:
# 2. Постройте матрицу корреляций - назовите df_salary_corr
df_salary_corr = df_salary_encoded.corr()
df_salary_corr

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,age_range
Age,1.000000,-0.110763,0.296143,0.262828,0.937585,0.727987,0.463644
Gender,-0.110763,1.000000,0.059663,0.020605,-0.088253,-0.124552,-0.063483
Education Level,0.296143,0.059663,1.000000,0.283569,0.271514,0.176724,0.228383
Job Title,0.262828,0.020605,0.283569,1.000000,0.185801,0.026857,0.198643
Years of Experience,0.937585,-0.088253,0.271514,0.185801,1.000000,0.808962,0.404573
Salary,0.727987,-0.124552,0.176724,0.026857,0.808962,1.000000,0.206950
age_range,0.463644,-0.063483,0.228383,0.198643,0.404573,0.206950,1.000000

In [79]:
# 3. Нарисуйте HeatMap
fig = px.imshow(df_salary_corr,
                x=df_salary_corr.columns,
                y=df_salary_corr.columns,
                text_auto = True,
                color_continuous_scale='RdBu_r',
                zmin=-1, zmax=1,
                title='Correlation Heatmap',
                width=800, height=800
                )
fig.show()