# <b><font color='forestgreen'>Polars: сложные фильтры и группировка</font></b>

### <font color='forestgreen'>1. Обработка пропусков</font>

In [2]:
# мпорт библиотек
import polars as pl

In [45]:
# Запишем данные из файла books_data_short.csv в dataframe df_books
df_books = pl.read_csv('../data/books_data_short.csv', null_values = 'NaN')
df_books

shape: (10, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year   в”† type         в”‚
в”‚ ---         в”† ---    в”† ---          в”‚
в”‚ f64         в”† f64    в”† str          в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 748.022957  в”† 1991.0 в”† encyclopedia в”‚
в”‚ 5849.487399 в”† null   в”† magazine     в”‚
в”‚ 546.485157  в”† 2021.0 в”† book         в”‚
в”‚ 1130.831881 в”† 1993.0 в”† magazine     в”‚
в”‚ 1247.822382 в”† 2002.0 в”† magazine     в”‚
в”‚ 1211.564183 в”† 2008.0 в”† magazine     в”‚
в”‚ 1651.054987 в”† 2009.0 в”† newspaper    в”‚
в”‚ 249.415919  в”† 1996.0 в”† encyclopedia в”‚
в”‚ 605.61386   в”† null   в”† magazine     в”‚
в”‚ 1370.04374  в”† 2008.0 в”† magazine     в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [44]:
df_books.describe()

shape: (9, 5)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ statistic  в”† price       в”† type      в”† year     в”† conditional в”‚
в”‚ ---        в”† ---         в”† ---       в”† ---      в”† ---         в”‚
в”‚ str        в”† f64         в”† str       в”† f64      в”† f64         в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ count      в”† 10.0        в”† 10        в”† 10.0     в”† 10.0        в”‚
в”‚ null_count в”† 0.0         в”† 0         в”† 0.0      в”† 0.0         в”‚
в”‚ mean       в”† 1461.034247 в”† null      в”† 2003.6   в”† 0.1         в”‚
в”‚ std        в”† 1600.839522 в”† null      в”† 8.884443 в”† null        в”‚
в”‚ min        в”† 249.415919  в”† book      в”† 1991.0   в”† 0.0         в”‚
в”‚ 25%        в”† 605.61386   в”† null      в”† 1996.0   в”† null        в”‚
в”‚ 50%        в”† 1211.564183 в”† null      в”† 2006.0   в”† null        в”‚
в”‚ 75%        в”† 1370.04374  в”† null      в”† 2008.0   в”† null        в”‚
в”‚ max        в”† 5849.487399 в”† newspaper в”† 2021.0   в”† 1.0         в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

##### <font color='forestgreen'>1.1. Определение недостающих данных</font>

In [4]:
# Проверка в столбце
df_books['year'].is_null().sum()

2

In [5]:
# Проверка в столбце
df_books['year'].null_count()

2

In [6]:
# Проверка в DataFrame
df_books.null_count()

shape: (1, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price в”† year в”† type в”‚
в”‚ ---   в”† ---  в”† ---  в”‚
в”‚ u32   в”† u32  в”† u32  в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 0     в”† 2    в”† 0    в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [46]:
df_books.filter(pl.col('year').is_null())

shape: (2, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year в”† type     в”‚
в”‚ ---         в”† ---  в”† ---      в”‚
в”‚ f64         в”† f64  в”† str      в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 5849.487399 в”† null в”† magazine в”‚
в”‚ 605.61386   в”† null в”† magazine в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

##### <font color='forestgreen'>1.2. Удаление пропущенных данных</font>

In [7]:
# Удаление всех пропущенных значений
df_books.drop_nulls() # Создает копию

shape: (8, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year   в”† type         в”‚
в”‚ ---         в”† ---    в”† ---          в”‚
в”‚ f64         в”† f64    в”† str          в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 748.022957  в”† 1991.0 в”† encyclopedia в”‚
в”‚ 546.485157  в”† 2021.0 в”† book         в”‚
в”‚ 1130.831881 в”† 1993.0 в”† magazine     в”‚
в”‚ 1247.822382 в”† 2002.0 в”† magazine     в”‚
в”‚ 1211.564183 в”† 2008.0 в”† magazine     в”‚
в”‚ 1651.054987 в”† 2009.0 в”† newspaper    в”‚
в”‚ 249.415919  в”† 1996.0 в”† encyclopedia в”‚
в”‚ 1370.04374  в”† 2008.0 в”† magazine     в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [51]:
# Удаление колонок со всеми NaN
df_books[[s.name for s in df_books if not (s.null_count() == df_books.height)]]

shape: (10, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year   в”† type         в”‚
в”‚ ---         в”† ---    в”† ---          в”‚
в”‚ f64         в”† f64    в”† str          в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 748.022957  в”† 1991.0 в”† encyclopedia в”‚
в”‚ 5849.487399 в”† null   в”† magazine     в”‚
в”‚ 546.485157  в”† 2021.0 в”† book         в”‚
в”‚ 1130.831881 в”† 1993.0 в”† magazine     в”‚
в”‚ 1247.822382 в”† 2002.0 в”† magazine     в”‚
в”‚ 1211.564183 в”† 2008.0 в”† magazine     в”‚
в”‚ 1651.054987 в”† 2009.0 в”† newspaper    в”‚
в”‚ 249.415919  в”† 1996.0 в”† encyclopedia в”‚
в”‚ 605.61386   в”† null   в”† magazine     в”‚
в”‚ 1370.04374  в”† 2008.0 в”† magazine     в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [9]:
for s in df_books:
    print(s.name)

price
year
type

##### <font color='forestgreen'>1.3. Заполнение пропущенных данных</font>
df.fill_null([константа, 'forward', 'backward', 'min', 'max', 'zero', 'one', 'mean'])

In [64]:
# Заполнение константой
df_books_filled = df_books.fill_null('unknown')
df_books_filled

shape: (10, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year   в”† type         в”‚
в”‚ ---         в”† ---    в”† ---          в”‚
в”‚ f64         в”† f64    в”† str          в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 748.022957  в”† 1991.0 в”† encyclopedia в”‚
в”‚ 5849.487399 в”† null   в”† magazine     в”‚
в”‚ 546.485157  в”† 2021.0 в”† book         в”‚
в”‚ 1130.831881 в”† 1993.0 в”† magazine     в”‚
в”‚ 1247.822382 в”† 2002.0 в”† magazine     в”‚
в”‚ 1211.564183 в”† 2008.0 в”† magazine     в”‚
в”‚ 1651.054987 в”† 2009.0 в”† newspaper    в”‚
в”‚ 249.415919  в”† 1996.0 в”† encyclopedia в”‚
в”‚ 605.61386   в”† null   в”† magazine     в”‚
в”‚ 1370.04374  в”† 2008.0 в”† magazine     в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [11]:
# Заполнение предыдущим значением
df_books.fill_null(strategy = 'forward')

shape: (10, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year   в”† type         в”‚
в”‚ ---         в”† ---    в”† ---          в”‚
в”‚ f64         в”† f64    в”† str          в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 748.022957  в”† 1991.0 в”† encyclopedia в”‚
в”‚ 5849.487399 в”† 1991.0 в”† magazine     в”‚
в”‚ 546.485157  в”† 2021.0 в”† book         в”‚
в”‚ 1130.831881 в”† 1993.0 в”† magazine     в”‚
в”‚ 1247.822382 в”† 2002.0 в”† magazine     в”‚
в”‚ 1211.564183 в”† 2008.0 в”† magazine     в”‚
в”‚ 1651.054987 в”† 2009.0 в”† newspaper    в”‚
в”‚ 249.415919  в”† 1996.0 в”† encyclopedia в”‚
в”‚ 605.61386   в”† 1996.0 в”† magazine     в”‚
в”‚ 1370.04374  в”† 2008.0 в”† magazine     в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

##### <font color='forestgreen'>1.4. Прямое и обратное заполнение</font>

In [12]:
df_books.with_columns(pl.col('year').backward_fill())

shape: (10, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year   в”† type         в”‚
в”‚ ---         в”† ---    в”† ---          в”‚
в”‚ f64         в”† f64    в”† str          в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 748.022957  в”† 1991.0 в”† encyclopedia в”‚
в”‚ 5849.487399 в”† 2021.0 в”† magazine     в”‚
в”‚ 546.485157  в”† 2021.0 в”† book         в”‚
в”‚ 1130.831881 в”† 1993.0 в”† magazine     в”‚
в”‚ 1247.822382 в”† 2002.0 в”† magazine     в”‚
в”‚ 1211.564183 в”† 2008.0 в”† magazine     в”‚
в”‚ 1651.054987 в”† 2009.0 в”† newspaper    в”‚
в”‚ 249.415919  в”† 1996.0 в”† encyclopedia в”‚
в”‚ 605.61386   в”† 2008.0 в”† magazine     в”‚
в”‚ 1370.04374  в”† 2008.0 в”† magazine     в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

##### <font color='forestgreen'>1.5. нтерполяция</font>
нтерполяция подразумевает оценку пропущенных значений на основе соседних точек данных.

In [13]:
df_books = df_books.interpolate()
df_books

shape: (10, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year   в”† type         в”‚
в”‚ ---         в”† ---    в”† ---          в”‚
в”‚ f64         в”† f64    в”† str          в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 748.022957  в”† 1991.0 в”† encyclopedia в”‚
в”‚ 5849.487399 в”† 2006.0 в”† magazine     в”‚
в”‚ 546.485157  в”† 2021.0 в”† book         в”‚
в”‚ 1130.831881 в”† 1993.0 в”† magazine     в”‚
в”‚ 1247.822382 в”† 2002.0 в”† magazine     в”‚
в”‚ 1211.564183 в”† 2008.0 в”† magazine     в”‚
в”‚ 1651.054987 в”† 2009.0 в”† newspaper    в”‚
в”‚ 249.415919  в”† 1996.0 в”† encyclopedia в”‚
в”‚ 605.61386   в”† 2002.0 в”† magazine     в”‚
в”‚ 1370.04374  в”† 2008.0 в”† magazine     в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

### <font color='forestgreen'>2. зменение типов данных (кастинг)</font>
[DateTypes](https://docs.pola.rs/api/python/stable/reference/datatypes.html)

In [14]:
df_books['year'].cast(pl.Int32)

shape: (10,)
Series: 'year' [i32]
[
	1991
	2006
	2021
	1993
	2002
	2008
	2009
	1996
	2002
	2008
]

In [15]:
df_books = df_books.with_columns(
    pl.col('year').cast(pl.Int32)
)

In [16]:
# Переименование столбцов 
df_books.rename({'price':'Price'})

shape: (10, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ Price       в”† year в”† type         в”‚
в”‚ ---         в”† ---  в”† ---          в”‚
в”‚ f64         в”† i32  в”† str          в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 748.022957  в”† 1991 в”† encyclopedia в”‚
в”‚ 5849.487399 в”† 2006 в”† magazine     в”‚
в”‚ 546.485157  в”† 2021 в”† book         в”‚
в”‚ 1130.831881 в”† 1993 в”† magazine     в”‚
в”‚ 1247.822382 в”† 2002 в”† magazine     в”‚
в”‚ 1211.564183 в”† 2008 в”† magazine     в”‚
в”‚ 1651.054987 в”† 2009 в”† newspaper    в”‚
в”‚ 249.415919  в”† 1996 в”† encyclopedia в”‚
в”‚ 605.61386   в”† 2002 в”† magazine     в”‚
в”‚ 1370.04374  в”† 2008 в”† magazine     в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

### <font color='forestgreen'>3. Операции агрегации</font>

In [17]:
df_books['price'].sum()

14610.342465841382

In [18]:
df_books.select([
    pl.col("price").count().alias("count"),
    pl.col("price").null_count().alias("null_count"),
    pl.col("price").mean().alias("mean"),
    pl.col("price").std().alias("std_dev"),
    pl.col("price").median().alias("median"),
    pl.col("price").min().alias("min"),
    pl.col("price").quantile(0.25).alias("25%"),
    pl.col("price").quantile(0.5).alias("50%"),
    pl.col("price").quantile(0.75).alias("75%"),
    pl.col("price").max().alias("max"),
])

shape: (1, 10)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ count в”† null_count в”† mean       в”† std_dev    в”† вЂ¦ в”† 25%       в”† 50%       в”† 75%       в”† max       в”‚
в”‚ ---   в”† ---        в”† ---        в”† ---        в”†   в”† ---       в”† ---       в”† ---       в”† ---       в”‚
в”‚ u32   в”† u32        в”† f64        в”† f64        в”†   в”† f64       в”† f64       в”† f64       в”† f64       в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 10    в”† 0          в”† 1461.03424 в”† 1600.83952 в”† вЂ¦ в”† 605.61386 в”† 1211.5641 в”† 1370.0437 в”† 5849.4873 в”‚
в”‚       в”†            в”† 7          в”† 2          в”†   в”†           в”† 83        в”† 4         в”† 99        в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

### <font color='forestgreen'>4. Группировка</font>

In [19]:
# group_by
df_books.group_by('year').len() #вместо count

shape: (8, 2)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ year в”† len в”‚
в”‚ ---  в”† --- в”‚
в”‚ i32  в”† u32 в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 2009 в”† 1   в”‚
в”‚ 1993 в”† 1   в”‚
в”‚ 2008 в”† 2   в”‚
в”‚ 1996 в”† 1   в”‚
в”‚ 2021 в”† 1   в”‚
в”‚ 2002 в”† 2   в”‚
в”‚ 1991 в”† 1   в”‚
в”‚ 2006 в”† 1   в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [20]:
# несколько функций аггрегаций
df_books.group_by('type').agg(
    [
        pl.mean('price').alias('mean_price'),
        pl.median('year').alias('median_year'),
        pl.len().alias('count')
    ])

shape: (4, 4)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ type         в”† mean_price  в”† median_year в”† count в”‚
в”‚ ---          в”† ---         в”† ---         в”† ---   в”‚
в”‚ str          в”† f64         в”† f64         в”† u32   в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ magazine     в”† 1902.560574 в”† 2004.0      в”† 6     в”‚
в”‚ book         в”† 546.485157  в”† 2021.0      в”† 1     в”‚
в”‚ encyclopedia в”† 498.719438  в”† 1993.5      в”† 2     в”‚
в”‚ newspaper    в”† 1651.054987 в”† 2009.0      в”† 1     в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [21]:
df_books.pivot("type", index="year", values="price", aggregate_function = 'mean')

shape: (8, 5)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ year в”† encyclopedia в”† magazine    в”† book       в”† newspaper   в”‚
в”‚ ---  в”† ---          в”† ---         в”† ---        в”† ---         в”‚
в”‚ i32  в”† f64          в”† f64         в”† f64        в”† f64         в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 1991 в”† 748.022957   в”† null        в”† null       в”† null        в”‚
в”‚ 2006 в”† null         в”† 5849.487399 в”† null       в”† null        в”‚
в”‚ 2021 в”† null         в”† null        в”† 546.485157 в”† null        в”‚
в”‚ 1993 в”† null         в”† 1130.831881 в”† null       в”† null        в”‚
в”‚ 2002 в”† null         в”† 926.718121  в”† null       в”† null        в”‚
в”‚ 2008 в”† null         в”† 1290.803962 в”† null       в”† null        в”‚
в”‚ 2009 в”† null         в”† null        в”† null       в”† 1651.054987 в”‚
в”‚ 1996 в”† 249.415919   в”† null        в”† null       в”† null        в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

### <font color='forestgreen'>5. Оконные функции</font>

<b>Базовый синтаксис: </b>
df.with_columns( pl.col("target_column").agg_function().over("group_column") )

- <i>pl.col("target_column")</i> – столбец, к которому применяется агрегационная функция.
- <i>agg_function()</i> – агрегационная функция (min, max, sum, mean и т.д.).
- <i>over("group_column")</i> – столбец (или список столбцов), по которому создается окно.

In [22]:
df_books.with_columns([
    pl.col("price").mean().over('type').alias("mean_price_by_type"),
    pl.col("price").max().over('type').alias("max_price_by_type")
])

shape: (10, 5)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year в”† type         в”† mean_price_by_type в”† max_price_by_type в”‚
в”‚ ---         в”† ---  в”† ---          в”† ---                в”† ---               в”‚
в”‚ f64         в”† i32  в”† str          в”† f64                в”† f64               в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 748.022957  в”† 1991 в”† encyclopedia в”† 498.719438         в”† 748.022957        в”‚
в”‚ 5849.487399 в”† 2006 в”† magazine     в”† 1902.560574        в”† 5849.487399       в”‚
в”‚ 546.485157  в”† 2021 в”† book         в”† 546.485157         в”† 546.485157        в”‚
в”‚ 1130.831881 в”† 1993 в”† magazine     в”† 1902.560574        в”† 5849.487399       в”‚
в”‚ 1247.822382 в”† 2002 в”† magazine     в”† 1902.560574        в”† 5849.487399       в”‚
в”‚ 1211.564183 в”† 2008 в”† magazine     в”† 1902.560574        в”† 5849.487399       в”‚
в”‚ 1651.054987 в”† 2009 в”† newspaper    в”† 1651.054987        в”† 1651.054987       в”‚
в”‚ 249.415919  в”† 1996 в”† encyclopedia в”† 498.719438         в”† 748.022957        в”‚
в”‚ 605.61386   в”† 2002 в”† magazine     в”† 1902.560574        в”† 5849.487399       в”‚
в”‚ 1370.04374  в”† 2008 в”† magazine     в”† 1902.560574        в”† 5849.487399       в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [23]:
# Вычислим ранк каждого издания по году внутри типа издания
df_books.with_columns([
    pl.col("year").rank('dense', descending = False).over("type").alias("rank_year_by_type")
]).sort(by = ['type', "rank_year_by_type"])

shape: (10, 4)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year в”† type         в”† rank_year_by_type в”‚
в”‚ ---         в”† ---  в”† ---          в”† ---               в”‚
в”‚ f64         в”† i32  в”† str          в”† u32               в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 546.485157  в”† 2021 в”† book         в”† 1                 в”‚
в”‚ 748.022957  в”† 1991 в”† encyclopedia в”† 1                 в”‚
в”‚ 249.415919  в”† 1996 в”† encyclopedia в”† 2                 в”‚
в”‚ 1130.831881 в”† 1993 в”† magazine     в”† 1                 в”‚
в”‚ 1247.822382 в”† 2002 в”† magazine     в”† 2                 в”‚
в”‚ 605.61386   в”† 2002 в”† magazine     в”† 2                 в”‚
в”‚ 5849.487399 в”† 2006 в”† magazine     в”† 3                 в”‚
в”‚ 1211.564183 в”† 2008 в”† magazine     в”† 4                 в”‚
в”‚ 1370.04374  в”† 2008 в”† magazine     в”† 4                 в”‚
в”‚ 1651.054987 в”† 2009 в”† newspaper    в”† 1                 в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [59]:
# Вычислите ранг каждого издания по стоимости (чем выше стоимость - тем выше ранг) внутри каждого типа
df_books.with_columns([
    pl.col("price").rank('dense', descending = True).over("type").alias("rank_price_by_type")
]).sort(by = ['type', "rank_price_by_type"])

shape: (10, 4)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year   в”† type         в”† rank_price_by_type в”‚
в”‚ ---         в”† ---    в”† ---          в”† ---                в”‚
в”‚ f64         в”† f64    в”† str          в”† u32                в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 546.485157  в”† 2021.0 в”† book         в”† 1                  в”‚
в”‚ 748.022957  в”† 1991.0 в”† encyclopedia в”† 1                  в”‚
в”‚ 249.415919  в”† 1996.0 в”† encyclopedia в”† 2                  в”‚
в”‚ 5849.487399 в”† null   в”† magazine     в”† 1                  в”‚
в”‚ 1370.04374  в”† 2008.0 в”† magazine     в”† 2                  в”‚
в”‚ 1247.822382 в”† 2002.0 в”† magazine     в”† 3                  в”‚
в”‚ 1211.564183 в”† 2008.0 в”† magazine     в”† 4                  в”‚
в”‚ 1130.831881 в”† 1993.0 в”† magazine     в”† 5                  в”‚
в”‚ 605.61386   в”† null   в”† magazine     в”† 6                  в”‚
в”‚ 1651.054987 в”† 2009.0 в”† newspaper    в”† 1                  в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

### <font color='forestgreen'>6. Уникальные значения</font>

In [25]:
# Способ №1
df_books['price'].n_unique()

10

In [60]:
# Способ №2
df_books.select(pl.approx_n_unique("type")) #HyperLogLog++

shape: (1, 1)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ type в”‚
в”‚ ---  в”‚
в”‚ u32  в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 4    в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

### <font color='forestgreen'>7. Сложная фильтрация</font>

In [27]:
df_books.filter((pl.col('year') > 2002) & (pl.col('type') == 'magazine'))

shape: (3, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year в”† type     в”‚
в”‚ ---         в”† ---  в”† ---      в”‚
в”‚ f64         в”† i32  в”† str      в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 5849.487399 в”† 2006 в”† magazine в”‚
в”‚ 1211.564183 в”† 2008 в”† magazine в”‚
в”‚ 1370.04374  в”† 2008 в”† magazine в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [28]:
df_books.filter(~(pl.col('type') == 'encyclopedia')) # аналог NOT
df_books.filter(pl.col('type') != 'encyclopedia')

shape: (8, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year в”† type      в”‚
в”‚ ---         в”† ---  в”† ---       в”‚
в”‚ f64         в”† i32  в”† str       в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 5849.487399 в”† 2006 в”† magazine  в”‚
в”‚ 546.485157  в”† 2021 в”† book      в”‚
в”‚ 1130.831881 в”† 1993 в”† magazine  в”‚
в”‚ 1247.822382 в”† 2002 в”† magazine  в”‚
в”‚ 1211.564183 в”† 2008 в”† magazine  в”‚
в”‚ 1651.054987 в”† 2009 в”† newspaper в”‚
в”‚ 605.61386   в”† 2002 в”† magazine  в”‚
в”‚ 1370.04374  в”† 2008 в”† magazine  в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

##### <font color='forestgreen'>7.1. спользование функций для фильтрации</font>

In [29]:
def expensive(price):
    return price >= 5000

df_books.filter(expensive(pl.col('price')))

shape: (1, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year в”† type     в”‚
в”‚ ---         в”† ---  в”† ---      в”‚
в”‚ f64         в”† i32  в”† str      в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 5849.487399 в”† 2006 в”† magazine в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

##### <font color='forestgreen'>7.2. Цепочка фильтров</font>

In [30]:
df_books.filter(pl.col('price') > 1000).filter(pl.col('year') > 2000)

shape: (5, 3)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† year в”† type      в”‚
в”‚ ---         в”† ---  в”† ---       в”‚
в”‚ f64         в”† i32  в”† str       в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 5849.487399 в”† 2006 в”† magazine  в”‚
в”‚ 1247.822382 в”† 2002 в”† magazine  в”‚
в”‚ 1211.564183 в”† 2008 в”† magazine  в”‚
в”‚ 1651.054987 в”† 2009 в”† newspaper в”‚
в”‚ 1370.04374  в”† 2008 в”† magazine  в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

### <font color='forestgreen'>8. Условия</font>
Polars поддерживает условия типа if-else в выражениях с синтаксисом when, then, otherwise. Предикат помещается в выражение when, и когда он оценивается как true, применяется выражение then, в противном случае применяется выражение otherwise (по порядку).

In [31]:
df_books = df_books.select(
    pl.col('price'),
    pl.col('type'),
    pl.col('year'),
    pl.when(pl.col('year') > 2014)
    .then(pl.lit(True))
    .otherwise(pl.lit(False))
    .alias('conditional')
)
df_books

shape: (10, 4)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ price       в”† type         в”† year в”† conditional в”‚
в”‚ ---         в”† ---          в”† ---  в”† ---         в”‚
в”‚ f64         в”† str          в”† i32  в”† bool        в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 748.022957  в”† encyclopedia в”† 1991 в”† false       в”‚
в”‚ 5849.487399 в”† magazine     в”† 2006 в”† false       в”‚
в”‚ 546.485157  в”† book         в”† 2021 в”† true        в”‚
в”‚ 1130.831881 в”† magazine     в”† 1993 в”† false       в”‚
в”‚ 1247.822382 в”† magazine     в”† 2002 в”† false       в”‚
в”‚ 1211.564183 в”† magazine     в”† 2008 в”† false       в”‚
в”‚ 1651.054987 в”† newspaper    в”† 2009 в”† false       в”‚
в”‚ 249.415919  в”† encyclopedia в”† 1996 в”† false       в”‚
в”‚ 605.61386   в”† magazine     в”† 2002 в”† false       в”‚
в”‚ 1370.04374  в”† magazine     в”† 2008 в”† false       в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

### <font color='forestgreen'>9. Задача</font>

In [3]:
# Загрузка данных
# import seaborn as sns
df_penguins = pl.DataFrame(sns.load_dataset('penguins'))
df_penguins

shape: (344, 7)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ species в”† island    в”† bill_length_mm в”† bill_depth_mm в”† flipper_length_mm в”† body_mass_g в”† sex    в”‚
в”‚ ---     в”† ---       в”† ---            в”† ---           в”† ---               в”† ---         в”† ---    в”‚
в”‚ str     в”† str       в”† f64            в”† f64           в”† f64               в”† f64         в”† str    в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ Adelie  в”† Torgersen в”† 39.1           в”† 18.7          в”† 181.0             в”† 3750.0      в”† Male   в”‚
в”‚ Adelie  в”† Torgersen в”† 39.5           в”† 17.4          в”† 186.0             в”† 3800.0      в”† Female в”‚
в”‚ Adelie  в”† Torgersen в”† 40.3           в”† 18.0          в”† 195.0             в”† 3250.0      в”† Female в”‚
в”‚ Adelie  в”† Torgersen в”† null           в”† null          в”† null              в”† null        в”† null   в”‚
в”‚ Adelie  в”† Torgersen в”† 36.7           в”† 19.3          в”† 193.0             в”† 3450.0      в”† Female в”‚
в”‚ вЂ¦       в”† вЂ¦         в”† вЂ¦              в”† вЂ¦             в”† вЂ¦                 в”† вЂ¦           в”† вЂ¦      в”‚
в”‚ Gentoo  в”† Biscoe    в”† null           в”† null          в”† null              в”† null        в”† null   в”‚
в”‚ Gentoo  в”† Biscoe    в”† 46.8           в”† 14.3          в”† 215.0             в”† 4850.0      в”† Female в”‚
в”‚ Gentoo  в”† Biscoe    в”† 50.4           в”† 15.7          в”† 222.0             в”† 5750.0      в”† Male   в”‚
в”‚ Gentoo  в”† Biscoe    в”† 45.2           в”† 14.8          в”† 212.0             в”† 5200.0      в”† Female в”‚
в”‚ Gentoo  в”† Biscoe    в”† 49.9           в”† 16.1          в”† 213.0             в”† 5400.0      в”† Male   в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [4]:
# Посчитать количество пропусков по каждому столбцу.
df_penguins.describe()
df_penguins.null_count()

shape: (1, 7)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ species в”† island в”† bill_length_mm в”† bill_depth_mm в”† flipper_length_mm в”† body_mass_g в”† sex в”‚
в”‚ ---     в”† ---    в”† ---            в”† ---           в”† ---               в”† ---         в”† --- в”‚
в”‚ u32     в”† u32    в”† u32            в”† u32           в”† u32               в”† u32         в”† u32 в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ 0       в”† 0      в”† 2              в”† 2             в”† 2                 в”† 2           в”† 11  в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [5]:
# Заполнить пропуски в bill_length_mm и bill_depth_mm средним значением по виду (species).
# Пропуски в sex заполнить "Unknown".
df_penguins_null = df_penguins.with_columns([
    pl.col("bill_length_mm").fill_null(strategy='mean'),
    pl.col("bill_depth_mm").fill_null(strategy='mean'),
    pl.col("sex").fill_null("Unknown")
])
df_penguins_null

shape: (344, 7)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ species в”† island    в”† bill_length_mm в”† bill_depth_mm в”† flipper_length_mm в”† body_mass_g в”† sex     в”‚
в”‚ ---     в”† ---       в”† ---            в”† ---           в”† ---               в”† ---         в”† ---     в”‚
в”‚ str     в”† str       в”† f64            в”† f64           в”† f64               в”† f64         в”† str     в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ Adelie  в”† Torgersen в”† 39.1           в”† 18.7          в”† 181.0             в”† 3750.0      в”† Male    в”‚
в”‚ Adelie  в”† Torgersen в”† 39.5           в”† 17.4          в”† 186.0             в”† 3800.0      в”† Female  в”‚
в”‚ Adelie  в”† Torgersen в”† 40.3           в”† 18.0          в”† 195.0             в”† 3250.0      в”† Female  в”‚
в”‚ Adelie  в”† Torgersen в”† 43.92193       в”† 17.15117      в”† null              в”† null        в”† Unknown в”‚
в”‚ Adelie  в”† Torgersen в”† 36.7           в”† 19.3          в”† 193.0             в”† 3450.0      в”† Female  в”‚
в”‚ вЂ¦       в”† вЂ¦         в”† вЂ¦              в”† вЂ¦             в”† вЂ¦                 в”† вЂ¦           в”† вЂ¦       в”‚
в”‚ Gentoo  в”† Biscoe    в”† 43.92193       в”† 17.15117      в”† null              в”† null        в”† Unknown в”‚
в”‚ Gentoo  в”† Biscoe    в”† 46.8           в”† 14.3          в”† 215.0             в”† 4850.0      в”† Female  в”‚
в”‚ Gentoo  в”† Biscoe    в”† 50.4           в”† 15.7          в”† 222.0             в”† 5750.0      в”† Male    в”‚
в”‚ Gentoo  в”† Biscoe    в”† 45.2           в”† 14.8          в”† 212.0             в”† 5200.0      в”† Female  в”‚
в”‚ Gentoo  в”† Biscoe    в”† 49.9           в”† 16.1          в”† 213.0             в”† 5400.0      в”† Male    в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [6]:
# Посчитать среднюю массу тела (body_mass_g) и среднюю длину плавника (flipper_length_mm) по виду и полу.
df_penguins_mean = df_penguins.group_by(['species', 'sex']).agg([
    pl.mean("body_mass_g").alias("mean_body_mass_g"),
    pl.mean("flipper_length_mm").alias("mean_flipper_length_mm")
])
df_penguins_mean

shape: (8, 4)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ species   в”† sex    в”† mean_body_mass_g в”† mean_flipper_length_mm в”‚
в”‚ ---       в”† ---    в”† ---              в”† ---                    в”‚
в”‚ str       в”† str    в”† f64              в”† f64                    в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ Chinstrap в”† Male   в”† 3938.970588      в”† 199.911765             в”‚
в”‚ Adelie    в”† Female в”† 3368.835616      в”† 187.794521             в”‚
в”‚ Gentoo    в”† Male   в”† 5484.836066      в”† 221.540984             в”‚
в”‚ Gentoo    в”† null   в”† 4587.5           в”† 215.75                 в”‚
в”‚ Gentoo    в”† Female в”† 4679.741379      в”† 212.706897             в”‚
в”‚ Chinstrap в”† Female в”† 3527.205882      в”† 191.735294             в”‚
в”‚ Adelie    в”† Male   в”† 4043.493151      в”† 192.410959             в”‚
в”‚ Adelie    в”† null   в”† 3540.0           в”† 185.6                  в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [7]:
# Сделать pivot-таблицу: индекс — species, колонки — sex, значения — средняя масса тела (body_mass_g).
df_penguins.pivot(index="species", columns="sex", values="body_mass_g", aggregate_function = 'mean')

C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_26768\1279533458.py:2: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  df_penguins.pivot(index="species", columns="sex", values="body_mass_g", aggregate_function = 'mean')

shape: (3, 4)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ species   в”† Male        в”† Female      в”† null   в”‚
в”‚ ---       в”† ---         в”† ---         в”† ---    в”‚
в”‚ str       в”† f64         в”† f64         в”† f64    в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ Adelie    в”† 4043.493151 в”† 3368.835616 в”† 3540.0 в”‚
в”‚ Chinstrap в”† 3938.970588 в”† 3527.205882 в”† null   в”‚
в”‚ Gentoo    в”† 5484.836066 в”† 4679.741379 в”† 4587.5 в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [8]:
# Оконные функции
# Добавить колонку rang_mass — ранг каждого пингвина в зависимости от массы тела внутри вида
df_penguins.with_columns(
    pl.col("body_mass_g").rank('dense', descending = True).over("species").alias("rang_mass")
).sort(by = ['species', "rang_mass"])

shape: (344, 8)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ species в”† island    в”† bill_length в”† bill_depth_ в”† flipper_len в”† body_mass_g в”† sex    в”† rang_mass в”‚
в”‚ ---     в”† ---       в”† _mm         в”† mm          в”† gth_mm      в”† ---         в”† ---    в”† ---       в”‚
в”‚ str     в”† str       в”† ---         в”† ---         в”† ---         в”† f64         в”† str    в”† u32       в”‚
в”‚         в”†           в”† f64         в”† f64         в”† f64         в”†             в”†        в”†           в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ Adelie  в”† Torgersen в”† null        в”† null        в”† null        в”† null        в”† null   в”† null      в”‚
в”‚ Adelie  в”† Biscoe    в”† 43.2        в”† 19.0        в”† 197.0       в”† 4775.0      в”† Male   в”† 1         в”‚
в”‚ Adelie  в”† Biscoe    в”† 41.0        в”† 20.0        в”† 203.0       в”† 4725.0      в”† Male   в”† 2         в”‚
в”‚ Adelie  в”† Torgersen в”† 42.9        в”† 17.6        в”† 196.0       в”† 4700.0      в”† Male   в”† 3         в”‚
в”‚ Adelie  в”† Torgersen в”† 39.2        в”† 19.6        в”† 195.0       в”† 4675.0      в”† Male   в”† 4         в”‚
в”‚ вЂ¦       в”† вЂ¦         в”† вЂ¦           в”† вЂ¦           в”† вЂ¦           в”† вЂ¦           в”† вЂ¦      в”† вЂ¦         в”‚
в”‚ Gentoo  в”† Biscoe    в”† 45.3        в”† 13.8        в”† 208.0       в”† 4200.0      в”† Female в”† 44        в”‚
в”‚ Gentoo  в”† Biscoe    в”† 45.5        в”† 13.9        в”† 210.0       в”† 4200.0      в”† Female в”† 44        в”‚
в”‚ Gentoo  в”† Biscoe    в”† 42.0        в”† 13.5        в”† 210.0       в”† 4150.0      в”† Female в”† 45        в”‚
в”‚ Gentoo  в”† Biscoe    в”† 44.5        в”† 14.3        в”† 216.0       в”† 4100.0      в”† null   в”† 46        в”‚
в”‚ Gentoo  в”† Biscoe    в”† 42.7        в”† 13.7        в”† 208.0       в”† 3950.0      в”† Female в”† 47        в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [9]:
# Сложная фильтрация и цепочка фильтров
# Выбрать строки, где body_mass_g > 4000 и flipper_length_mm > 200
df_penguins.filter((pl.col('body_mass_g') > 4000) & (pl.col('flipper_length_mm') > 200))

shape: (137, 7)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ species   в”† island в”† bill_length_mm в”† bill_depth_mm в”† flipper_length_mm в”† body_mass_g в”† sex    в”‚
в”‚ ---       в”† ---    в”† ---            в”† ---           в”† ---               в”† ---         в”† ---    в”‚
в”‚ str       в”† str    в”† f64            в”† f64           в”† f64               в”† f64         в”† str    в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ Adelie    в”† Dream  в”† 41.1           в”† 18.1          в”† 205.0             в”† 4300.0      в”† Male   в”‚
в”‚ Adelie    в”† Dream  в”† 40.8           в”† 18.9          в”† 208.0             в”† 4300.0      в”† Male   в”‚
в”‚ Adelie    в”† Biscoe в”† 41.0           в”† 20.0          в”† 203.0             в”† 4725.0      в”† Male   в”‚
в”‚ Chinstrap в”† Dream  в”† 52.0           в”† 18.1          в”† 201.0             в”† 4050.0      в”† Male   в”‚
в”‚ Chinstrap в”† Dream  в”† 50.5           в”† 19.6          в”† 201.0             в”† 4050.0      в”† Male   в”‚
в”‚ вЂ¦         в”† вЂ¦      в”† вЂ¦              в”† вЂ¦             в”† вЂ¦                 в”† вЂ¦           в”† вЂ¦      в”‚
в”‚ Gentoo    в”† Biscoe в”† 47.2           в”† 13.7          в”† 214.0             в”† 4925.0      в”† Female в”‚
в”‚ Gentoo    в”† Biscoe в”† 46.8           в”† 14.3          в”† 215.0             в”† 4850.0      в”† Female в”‚
в”‚ Gentoo    в”† Biscoe в”† 50.4           в”† 15.7          в”† 222.0             в”† 5750.0      в”† Male   в”‚
в”‚ Gentoo    в”† Biscoe в”† 45.2           в”† 14.8          в”† 212.0             в”† 5200.0      в”† Female в”‚
в”‚ Gentoo    в”† Biscoe в”† 49.9           в”† 16.1          в”† 213.0             в”† 5400.0      в”† Male   в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”

In [10]:
# Создать колонку heavy со значением "Yes", если body_mass_g > 5000, иначе "No".
df_penguins.with_columns(
    pl.when(pl.col('body_mass_g') > 5000)
    .then(pl.lit("Yes"))
    .otherwise(pl.lit("No"))
    .alias("heavy")
)

shape: (344, 8)
в”Њв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ђ
в”‚ species в”† island    в”† bill_length_m в”† bill_depth_m в”† flipper_leng в”† body_mass_g в”† sex    в”† heavy в”‚
в”‚ ---     в”† ---       в”† m             в”† m            в”† th_mm        в”† ---         в”† ---    в”† ---   в”‚
в”‚ str     в”† str       в”† ---           в”† ---          в”† ---          в”† f64         в”† str    в”† str   в”‚
в”‚         в”†           в”† f64           в”† f64          в”† f64          в”†             в”†        в”†       в”‚
в•ћв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Єв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•Ў
в”‚ Adelie  в”† Torgersen в”† 39.1          в”† 18.7         в”† 181.0        в”† 3750.0      в”† Male   в”† No    в”‚
в”‚ Adelie  в”† Torgersen в”† 39.5          в”† 17.4         в”† 186.0        в”† 3800.0      в”† Female в”† No    в”‚
в”‚ Adelie  в”† Torgersen в”† 40.3          в”† 18.0         в”† 195.0        в”† 3250.0      в”† Female в”† No    в”‚
в”‚ Adelie  в”† Torgersen в”† null          в”† null         в”† null         в”† null        в”† null   в”† No    в”‚
в”‚ Adelie  в”† Torgersen в”† 36.7          в”† 19.3         в”† 193.0        в”† 3450.0      в”† Female в”† No    в”‚
в”‚ вЂ¦       в”† вЂ¦         в”† вЂ¦             в”† вЂ¦            в”† вЂ¦            в”† вЂ¦           в”† вЂ¦      в”† вЂ¦     в”‚
в”‚ Gentoo  в”† Biscoe    в”† null          в”† null         в”† null         в”† null        в”† null   в”† No    в”‚
в”‚ Gentoo  в”† Biscoe    в”† 46.8          в”† 14.3         в”† 215.0        в”† 4850.0      в”† Female в”† No    в”‚
в”‚ Gentoo  в”† Biscoe    в”† 50.4          в”† 15.7         в”† 222.0        в”† 5750.0      в”† Male   в”† Yes   в”‚
в”‚ Gentoo  в”† Biscoe    в”† 45.2          в”† 14.8         в”† 212.0        в”† 5200.0      в”† Female в”† Yes   в”‚
в”‚ Gentoo  в”† Biscoe    в”† 49.9          в”† 16.1         в”† 213.0        в”† 5400.0      в”† Male   в”† Yes   в”‚
в””в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”