1. Загрузите данные на свой жёсткий диск.

2. Считайте их в polars.

3. Посчитайте уникальное количество кодов категорий двумя разными способами.

4. Замените отсутствующие коды категорий значением по выбору и убедитесь, что описательная статистика поменялась.

5. На основе оконных функций постройте поле, состоящее из максимальной цены в разбивке по коду категории.

6. Постройте новое поле, принимающее значение True, если цена больше средней цены, и False в ином случае.

In [ ]:
import polars as pl
# 1. Загрузка данных
events = pl.read_csv('events.csv')
events

shape: (885_129, 9)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬────────┬───────────┬───────────┐
│ event_time ┆ event_type ┆ product_i ┆ category_ ┆ … ┆ brand     ┆ price  ┆ user_id   ┆ user_sess │
│ ---        ┆ ---        ┆ d         ┆ id        ┆   ┆ ---       ┆ ---    ┆ ---       ┆ ion       │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ str       ┆ f64    ┆ i64       ┆ ---       │
│            ┆            ┆ i64       ┆ i64       ┆   ┆           ┆        ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ 2020-09-24 ┆ view       ┆ 1996170   ┆ 214441592 ┆ … ┆ null      ┆ 31.9   ┆ 151591562 ┆ LJuJVLEjP │
│ 11:57:06   ┆            ┆           ┆ 252845271 ┆   ┆           ┆        ┆ 551938826 ┆ T         │
│ UTC        ┆            ┆           ┆ 5         ┆   ┆           ┆        ┆ 7         ┆           │
│ 2020-09-24 ┆ view       ┆ 139905    ┆ 214441592 ┆ … ┆ zalman    ┆ 17.16  ┆ 151591562 ┆ tdicluNnR │
│ 11:57:26   ┆            ┆           ┆ 693247202 ┆   ┆           ┆        ┆ 551938041 ┆ Y         │
│ UTC        ┆            ┆           ┆ 7         ┆   ┆           ┆        ┆ 1         ┆           │
│ 2020-09-24 ┆ view       ┆ 215454    ┆ 214441592 ┆ … ┆ null      ┆ 9.81   ┆ 151591562 ┆ 4TMArHtXQ │
│ 11:57:27   ┆            ┆           ┆ 715896444 ┆   ┆           ┆        ┆ 551323851 ┆ y         │
│ UTC        ┆            ┆           ┆ 9         ┆   ┆           ┆        ┆ 5         ┆           │
│ 2020-09-24 ┆ view       ┆ 635807    ┆ 214441592 ┆ … ┆ pantum    ┆ 113.81 ┆ 151591562 ┆ aGFYrNgC0 │
│ 11:57:33   ┆            ┆           ┆ 310726668 ┆   ┆           ┆        ┆ 551901435 ┆ 8         │
│ UTC        ┆            ┆           ┆ 2         ┆   ┆           ┆        ┆ 6         ┆           │
│ 2020-09-24 ┆ view       ┆ 3658723   ┆ 214441592 ┆ … ┆ cameronsi ┆ 15.87  ┆ 151591562 ┆ aa4mmk0kw │
│ 11:57:36   ┆            ┆           ┆ 116949818 ┆   ┆ no        ┆        ┆ 551074334 ┆ Q         │
│ UTC        ┆            ┆           ┆ 4         ┆   ┆           ┆        ┆ 4         ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …      ┆ …         ┆ …         │
│ 2021-02-28 ┆ view       ┆ 953226    ┆ 214441592 ┆ … ┆ null      ┆ 219.94 ┆ 151591562 ┆ FRLqIttxK │
│ 23:55:01   ┆            ┆           ┆ 755322903 ┆   ┆           ┆        ┆ 561102373 ┆ U         │
│ UTC        ┆            ┆           ┆ 7         ┆   ┆           ┆        ┆ 0         ┆           │
│ 2021-02-28 ┆ view       ┆ 1715907   ┆ 214441592 ┆ … ┆ starwind  ┆ 80.03  ┆ 151591562 ┆ g6WqPf50M │
│ 23:58:05   ┆            ┆           ┆ 704991254 ┆   ┆           ┆        ┆ 561102401 ┆ a         │
│ UTC        ┆            ┆           ┆ 2         ┆   ┆           ┆        ┆ 4         ┆           │
│ 2021-02-28 ┆ view       ┆ 4170534   ┆ 214441593 ┆ … ┆ amazfit   ┆ 64.92  ┆ 151591562 ┆ xNIJBqZdk │
│ 23:58:09   ┆            ┆           ┆ 936438942 ┆   ┆           ┆        ┆ 561102402 ┆ d         │
│ UTC        ┆            ┆           ┆ 3         ┆   ┆           ┆        ┆ 0         ┆           │
│ 2021-02-28 ┆ view       ┆ 888273    ┆ 214441592 ┆ … ┆ null      ┆ 10.16  ┆ 151591562 ┆ 9pCbKMIcS │
│ 23:58:14   ┆            ┆           ┆ 193286153 ┆   ┆           ┆        ┆ 561102403 ┆ x         │
│ UTC        ┆            ┆           ┆ 1         ┆   ┆           ┆        ┆ 0         ┆           │
│ 2021-02-28 ┆ view       ┆ 743182    ┆ 214441593 ┆ … ┆ kada      ┆ 65.08  ┆ 151591562 ┆ BejOXRngE │
│ 23:59:09   ┆            ┆           ┆ 563145876 ┆   ┆           ┆        ┆ 555608777 ┆ W         │
│ UTC        ┆            ┆           ┆ 1         ┆   ┆           ┆        ┆ 5         ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴────────┴───────────┴───────────┘

In [ ]:
# 2. Статистика по данным
events.describe()

shape: (9, 10)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ event_time ┆ event_typ ┆ product_i ┆ … ┆ brand  ┆ price     ┆ user_id   ┆ user_sess │
│ ---        ┆ ---        ┆ e         ┆ d         ┆   ┆ ---    ┆ ---       ┆ ---       ┆ ion       │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ str    ┆ f64       ┆ f64       ┆ ---       │
│            ┆            ┆ str       ┆ f64       ┆   ┆        ┆           ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 885129     ┆ 885129    ┆ 885129.0  ┆ … ┆ 672765 ┆ 885129.0  ┆ 885129.0  ┆ 884964    │
│ null_count ┆ 0          ┆ 0         ┆ 0.0       ┆ … ┆ 212364 ┆ 0.0       ┆ 0.0       ┆ 165       │
│ mean       ┆ null       ┆ null      ┆ 1.9066e6  ┆ … ┆ null   ┆ 146.32871 ┆ 1.5159e18 ┆ null      │
│            ┆            ┆           ┆           ┆   ┆        ┆ 3         ┆           ┆           │
│ std        ┆ null       ┆ null      ┆ 1.4587e6  ┆ … ┆ null   ┆ 296.80768 ┆ 3.5549e7  ┆ null      │
│            ┆            ┆           ┆           ┆   ┆        ┆ 3         ┆           ┆           │
│ min        ┆ 2020-09-24 ┆ cart      ┆ 102.0     ┆ … ┆ a-data ┆ 0.22      ┆ 1.5159e18 ┆ 000AMhYaQ │
│            ┆ 11:57:06   ┆           ┆           ┆   ┆        ┆           ┆           ┆ u         │
│            ┆ UTC        ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 25%        ┆ null       ┆ null      ┆ 698803.0  ┆ … ┆ null   ┆ 26.46     ┆ 1.5159e18 ┆ null      │
│ 50%        ┆ null       ┆ null      ┆ 1.452883e ┆ … ┆ null   ┆ 65.71     ┆ 1.5159e18 ┆ null      │
│            ┆            ┆           ┆ 6         ┆   ┆        ┆           ┆           ┆           │
│ 75%        ┆ null       ┆ null      ┆ 3.721194e ┆ … ┆ null   ┆ 190.49    ┆ 1.5159e18 ┆ null      │
│            ┆            ┆           ┆ 6         ┆   ┆        ┆           ┆           ┆           │
│ max        ┆ 2021-02-28 ┆ view      ┆ 4.18388e6 ┆ … ┆ zyxel  ┆ 64771.06  ┆ 1.5159e18 ┆ zzzYMiLcf │
│            ┆ 23:59:09   ┆           ┆           ┆   ┆        ┆           ┆           ┆ 7         │
│            ┆ UTC        ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

In [ ]:
# 3. Подсчет уникальных кодов категорий разными способами
print(f"Через Unique: {events['category_code'].n_unique()}")
print("-"*50)
print(f"Через select: {events.select(pl.approx_n_unique('category_code'))}")
print("-"*50)
print(f"Через GroupBy: {events.group_by('category_code').len().shape[0]}")

Через Unique: 108
--------------------------------------------------
Через select: shape: (1, 1)
┌───────────────┐
│ category_code │
│ ---           │
│ u32           │
╞═══════════════╡
│ 108           │
└───────────────┘
--------------------------------------------------
Через GroupBy: 108

In [ ]:
# 4. Замените отсутствующие коды категорий значением по выбору и убедитесь, что описательная статистика поменялась.
events_filled = events.fill_null('unknown')
events_filled.describe()

shape: (9, 10)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ event_time ┆ event_typ ┆ product_i ┆ … ┆ brand  ┆ price     ┆ user_id   ┆ user_sess │
│ ---        ┆ ---        ┆ e         ┆ d         ┆   ┆ ---    ┆ ---       ┆ ---       ┆ ion       │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ str    ┆ f64       ┆ f64       ┆ ---       │
│            ┆            ┆ str       ┆ f64       ┆   ┆        ┆           ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 885129     ┆ 885129    ┆ 885129.0  ┆ … ┆ 885129 ┆ 885129.0  ┆ 885129.0  ┆ 885129    │
│ null_count ┆ 0          ┆ 0         ┆ 0.0       ┆ … ┆ 0      ┆ 0.0       ┆ 0.0       ┆ 0         │
│ mean       ┆ null       ┆ null      ┆ 1.9066e6  ┆ … ┆ null   ┆ 146.32871 ┆ 1.5159e18 ┆ null      │
│            ┆            ┆           ┆           ┆   ┆        ┆ 3         ┆           ┆           │
│ std        ┆ null       ┆ null      ┆ 1.4587e6  ┆ … ┆ null   ┆ 296.80768 ┆ 3.5549e7  ┆ null      │
│            ┆            ┆           ┆           ┆   ┆        ┆ 3         ┆           ┆           │
│ min        ┆ 2020-09-24 ┆ cart      ┆ 102.0     ┆ … ┆ a-data ┆ 0.22      ┆ 1.5159e18 ┆ 000AMhYaQ │
│            ┆ 11:57:06   ┆           ┆           ┆   ┆        ┆           ┆           ┆ u         │
│            ┆ UTC        ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 25%        ┆ null       ┆ null      ┆ 698803.0  ┆ … ┆ null   ┆ 26.46     ┆ 1.5159e18 ┆ null      │
│ 50%        ┆ null       ┆ null      ┆ 1.452883e ┆ … ┆ null   ┆ 65.71     ┆ 1.5159e18 ┆ null      │
│            ┆            ┆           ┆ 6         ┆   ┆        ┆           ┆           ┆           │
│ 75%        ┆ null       ┆ null      ┆ 3.721194e ┆ … ┆ null   ┆ 190.49    ┆ 1.5159e18 ┆ null      │
│            ┆            ┆           ┆ 6         ┆   ┆        ┆           ┆           ┆           │
│ max        ┆ 2021-02-28 ┆ view      ┆ 4.18388e6 ┆ … ┆ zyxel  ┆ 64771.06  ┆ 1.5159e18 ┆ zzzYMiLcf │
│            ┆ 23:59:09   ┆           ┆           ┆   ┆        ┆           ┆           ┆ 7         │
│            ┆ UTC        ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

In [ ]:
# Отфильтруйте теперь только те значения в столбике категроии коде которые не были заполнены и убедитесь, что там нет пропусков.
events_filled.filter(pl.col('category_code') == 'unknown')

shape: (236_219, 9)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬────────┬───────────┬───────────┐
│ event_time ┆ event_type ┆ product_i ┆ category_ ┆ … ┆ brand     ┆ price  ┆ user_id   ┆ user_sess │
│ ---        ┆ ---        ┆ d         ┆ id        ┆   ┆ ---       ┆ ---    ┆ ---       ┆ ion       │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ str       ┆ f64    ┆ i64       ┆ ---       │
│            ┆            ┆ i64       ┆ i64       ┆   ┆           ┆        ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ 2020-09-24 ┆ view       ┆ 215454    ┆ 214441592 ┆ … ┆ unknown   ┆ 9.81   ┆ 151591562 ┆ 4TMArHtXQ │
│ 11:57:27   ┆            ┆           ┆ 715896444 ┆   ┆           ┆        ┆ 551323851 ┆ y         │
│ UTC        ┆            ┆           ┆ 9         ┆   ┆           ┆        ┆ 5         ┆           │
│ 2020-09-24 ┆ view       ┆ 3658723   ┆ 214441592 ┆ … ┆ cameronsi ┆ 15.87  ┆ 151591562 ┆ aa4mmk0kw │
│ 11:57:36   ┆            ┆           ┆ 116949818 ┆   ┆ no        ┆        ┆ 551074334 ┆ Q         │
│ UTC        ┆            ┆           ┆ 4         ┆   ┆           ┆        ┆ 4         ┆           │
│ 2020-09-24 ┆ view       ┆ 657859    ┆ 214441593 ┆ … ┆ unknown   ┆ 34.17  ┆ 151591562 ┆ HEl15U7JV │
│ 11:58:25   ┆            ┆           ┆ 943149828 ┆   ┆           ┆        ┆ 551932057 ┆ y         │
│ UTC        ┆            ┆           ┆ 9         ┆   ┆           ┆        ┆ 0         ┆           │
│ 2020-09-24 ┆ view       ┆ 811491    ┆ 214441592 ┆ … ┆ ritmix    ┆ 33.32  ┆ 151591562 ┆ aFLc6y9kn │
│ 11:58:34   ┆            ┆           ┆ 637043527 ┆   ┆           ┆        ┆ 535620564 ┆ 4         │
│ UTC        ┆            ┆           ┆ 6         ┆   ┆           ┆        ┆ 7         ┆           │
│ 2020-09-24 ┆ view       ┆ 811491    ┆ 214441592 ┆ … ┆ ritmix    ┆ 33.32  ┆ 151591562 ┆ aFLc6y9kn │
│ 11:58:54   ┆            ┆           ┆ 637043527 ┆   ┆           ┆        ┆ 535620564 ┆ 4         │
│ UTC        ┆            ┆           ┆ 6         ┆   ┆           ┆        ┆ 7         ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …      ┆ …         ┆ …         │
│ 2021-02-28 ┆ view       ┆ 775400    ┆ 214441592 ┆ … ┆ unknown   ┆ 15.08  ┆ 151591562 ┆ TNWPE1GfY │
│ 23:36:07   ┆            ┆           ┆ 116949818 ┆   ┆           ┆        ┆ 561102205 ┆ 9         │
│ UTC        ┆            ┆           ┆ 4         ┆   ┆           ┆        ┆ 3         ┆           │
│ 2021-02-28 ┆ view       ┆ 1022663   ┆ 214441594 ┆ … ┆ cameronsi ┆ 35.24  ┆ 151591562 ┆ iERbMFYhh │
│ 23:38:11   ┆            ┆           ┆ 396134673 ┆   ┆ no        ┆        ┆ 561102225 ┆ x         │
│ UTC        ┆            ┆           ┆ 0         ┆   ┆           ┆        ┆ 3         ┆           │
│ 2021-02-28 ┆ view       ┆ 1502502   ┆ 214441593 ┆ … ┆ unknown   ┆ 83.97  ┆ 151591562 ┆ DLdrfrUb1 │
│ 23:39:41   ┆            ┆           ┆ 379435355 ┆   ┆           ┆        ┆ 561102237 ┆ z         │
│ UTC        ┆            ┆           ┆ 4         ┆   ┆           ┆        ┆ 2         ┆           │
│ 2021-02-28 ┆ view       ┆ 698926    ┆ 214441594 ┆ … ┆ makita    ┆ 244.29 ┆ 151591562 ┆ 3qLFAotCj │
│ 23:46:48   ┆            ┆           ┆ 235073395 ┆   ┆           ┆        ┆ 561050613 ┆ H         │
│ UTC        ┆            ┆           ┆ 1         ┆   ┆           ┆        ┆ 8         ┆           │
│ 2021-02-28 ┆ view       ┆ 953226    ┆ 214441592 ┆ … ┆ unknown   ┆ 219.94 ┆ 151591562 ┆ FRLqIttxK │
│ 23:55:01   ┆            ┆           ┆ 755322903 ┆   ┆           ┆        ┆ 561102373 ┆ U         │
│ UTC        ┆            ┆           ┆ 7         ┆   ┆           ┆        ┆ 0         ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴────────┴───────────┴───────────┘

In [ ]:
# 5. На основе оконных функций постройте поле, состоящее из максимальной цены в разбивке по коду категории.
events_filled.with_columns([
    pl.col("price")
    .max()
    .over("category_code")
    .alias("max_price_by_category")
    
]).sort(by = "max_price_by_category", descending = True)

shape: (885_129, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ event_time ┆ event_typ ┆ product_i ┆ category_ ┆ … ┆ price   ┆ user_id   ┆ user_sess ┆ max_price │
│ ---        ┆ e         ┆ d         ┆ id        ┆   ┆ ---     ┆ ---       ┆ ion       ┆ _by_categ │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64     ┆ i64       ┆ ---       ┆ ory       │
│            ┆ str       ┆ i64       ┆ i64       ┆   ┆         ┆           ┆ str       ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 2020-09-24 ┆ view      ┆ 889614    ┆ 214441592 ┆ … ┆ 45.35   ┆ 151591562 ┆ XKUzFI5Ve ┆ 64771.06  │
│ 13:25:13   ┆           ┆           ┆ 897090382 ┆   ┆         ┆ 551942088 ┆ 8         ┆           │
│ UTC        ┆           ┆           ┆ 7         ┆   ┆         ┆ 3         ┆           ┆           │
│ 2020-09-24 ┆ view      ┆ 889614    ┆ 214441592 ┆ … ┆ 45.35   ┆ 151591562 ┆ XKUzFI5Ve ┆ 64771.06  │
│ 13:25:29   ┆           ┆           ┆ 897090382 ┆   ┆         ┆ 551942088 ┆ 8         ┆           │
│ UTC        ┆           ┆           ┆ 7         ┆   ┆         ┆ 3         ┆           ┆           │
│ 2020-09-24 ┆ view      ┆ 1148993   ┆ 214441592 ┆ … ┆ 1057.35 ┆ 151591562 ┆ qI2ILCw35 ┆ 64771.06  │
│ 13:26:59   ┆           ┆           ┆ 240262359 ┆   ┆         ┆ 539943106 ┆ i         ┆           │
│ UTC        ┆           ┆           ┆ 1         ┆   ┆         ┆ 3         ┆           ┆           │
│ 2020-09-24 ┆ view      ┆ 1148993   ┆ 214441592 ┆ … ┆ 1057.35 ┆ 151591562 ┆ OFVAuTUNO ┆ 64771.06  │
│ 13:27:01   ┆           ┆           ┆ 240262359 ┆   ┆         ┆ 539943106 ┆ l         ┆           │
│ UTC        ┆           ┆           ┆ 1         ┆   ┆         ┆ 3         ┆           ┆           │
│ 2020-09-24 ┆ view      ┆ 911882    ┆ 214441592 ┆ … ┆ 580.56  ┆ 151591562 ┆ 13vnm8LKK ┆ 64771.06  │
│ 14:40:08   ┆           ┆           ┆ 240262359 ┆   ┆         ┆ 544566125 ┆ i         ┆           │
│ UTC        ┆           ┆           ┆ 1         ┆   ┆         ┆ 1         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ 2021-02-26 ┆ view      ┆ 565453    ┆ 214441594 ┆ … ┆ 1.57    ┆ 151591562 ┆ NrI4NDhz8 ┆ 10.14     │
│ 07:50:18   ┆           ┆           ┆ 079045282 ┆   ┆         ┆ 560974208 ┆ O         ┆           │
│ UTC        ┆           ┆           ┆ 0         ┆   ┆         ┆ 8         ┆           ┆           │
│ 2021-02-26 ┆ view      ┆ 565470    ┆ 214441594 ┆ … ┆ 1.57    ┆ 151591562 ┆ u5ZITjgqj ┆ 10.14     │
│ 11:21:44   ┆           ┆           ┆ 079045282 ┆   ┆         ┆ 560995609 ┆ t         ┆           │
│ UTC        ┆           ┆           ┆ 0         ┆   ┆         ┆ 8         ┆           ┆           │
│ 2021-02-26 ┆ view      ┆ 565470    ┆ 214441594 ┆ … ┆ 1.57    ┆ 151591562 ┆ FHb9Yy6mk ┆ 10.14     │
│ 22:09:57   ┆           ┆           ┆ 079045282 ┆   ┆         ┆ 561016200 ┆ 4         ┆           │
│ UTC        ┆           ┆           ┆ 0         ┆   ┆         ┆ 3         ┆           ┆           │
│ 2021-02-28 ┆ view      ┆ 565473    ┆ 214441594 ┆ … ┆ 5.9     ┆ 151591562 ┆ Z6rD8nyJ0 ┆ 10.14     │
│ 13:34:06   ┆           ┆           ┆ 079045282 ┆   ┆         ┆ 561085709 ┆ e         ┆           │
│ UTC        ┆           ┆           ┆ 0         ┆   ┆         ┆ 6         ┆           ┆           │
│ 2021-02-28 ┆ view      ┆ 565473    ┆ 214441594 ┆ … ┆ 5.9     ┆ 151591562 ┆ RQ5kVh1Vh ┆ 10.14     │
│ 14:50:07   ┆           ┆           ┆ 079045282 ┆   ┆         ┆ 561085709 ┆ q         ┆           │
│ UTC        ┆           ┆           ┆ 0         ┆   ┆         ┆ 6         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [ ]:
# 6. Постройте новое поле, принимающее значение True, если цена больше средней цены, и False в ином случае.
avg_price = events_filled.select(pl.col("price").mean()).item()
print(f"Средняя цена: {avg_price}")
events_bool = events_filled.select([
    pl.col("price"),
    pl.when(pl.col("price") > avg_price)
    .then(True)
    .otherwise(False)
    .alias("is_price_above_average")
])
display(events_bool)
print(f"Количество записей с ценой выше средней: {events_bool.filter(pl.col('is_price_above_average') == True).shape[0]}")
print(f"Количество записей с ценой ниже или равной средней: {events_bool.filter(pl.col('is_price_above_average') == False).shape[0]}")

Средняя цена: 146.3287134982585

shape: (885_129, 2)
┌────────┬────────────────────────┐
│ price  ┆ is_price_above_average │
│ ---    ┆ ---                    │
│ f64    ┆ bool                   │
╞════════╪════════════════════════╡
│ 31.9   ┆ false                  │
│ 17.16  ┆ false                  │
│ 9.81   ┆ false                  │
│ 113.81 ┆ false                  │
│ 15.87  ┆ false                  │
│ …      ┆ …                      │
│ 219.94 ┆ true                   │
│ 80.03  ┆ false                  │
│ 64.92  ┆ false                  │
│ 10.16  ┆ false                  │
│ 65.08  ┆ false                  │
└────────┴────────────────────────┘

Количество записей с ценой выше средней: 268850
Количество записей с ценой ниже или равной средней: 616279