In [2]:
# импорт библиотек
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats

1. Загрузите датасет titanic из библиотеки seaborn, определите столбцы с пустыми значениями и заполните их любым из возможных методов.

In [3]:
df_titanic = sns.load_dataset('titanic')
df_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
df_titanic.isna().sum()[df_titanic.isna().sum() > 0]

age            177
embarked         2
deck           688
embark_town      2
dtype: int64

In [5]:
conditions = [
    df_titanic["age"].isna(),
    df_titanic["age"] < 13,
    (df_titanic["age"] >= 13) & (df_titanic["age"] < 18),
    (df_titanic["age"] >= 18) & (df_titanic["age"] < 36),
    (df_titanic["age"] >= 36) & (df_titanic["age"] < 60),
    df_titanic["age"] >= 60
]

choices = ["unknown", "child", "teen", "young_adult", "adult", "senior"]

df_titanic["age_group"] = np.select(conditions, choices, default="unknown")
df_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,young_adult
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,adult
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,young_adult
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,young_adult
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,young_adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,young_adult
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,young_adult
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,unknown
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,young_adult
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,young_adult

In [6]:
display(df_titanic[df_titanic['embarked'].isna()])

display(df_titanic[df_titanic['embark_town'].isna()])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,adult
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,senior

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,adult
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,senior

In [7]:
counts = df_titanic["embark_town"].value_counts()
print(counts)

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [8]:
counts = df_titanic["embarked"].value_counts()
print(counts)

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [9]:
counts = df_titanic["age_group"].value_counts()
print(counts)

age_group
young_adult    384
adult          191
unknown        177
child           69
teen            44
senior          26
Name: count, dtype: int64

In [10]:
df_titanic.fillna({'age':df_titanic['age'].median(),
                   'embarked':df_titanic['embarked'].mode()[0],
                   'deck':df_titanic['deck'].mode()[0],
                   'embark_town': 'Unknown Town'}, inplace = True)

2. Загрузите датасет titanic из библиотеки seaborn, определите категориальную переменную и закодируйте её.

In [14]:
# display(pd.factorize(df_titanic['class'])[0])
# display(pd.factorize(df_titanic['embark_town'])[0])
df_titanic.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
age_group        object
dtype: object

In [ ]:
df_titanic['sex_encoded'] = pd.factorize(df_titanic['sex'])[0]
df_titanic['class_encoded'] = pd.factorize(df_titanic['class'])[0]
df_titanic['embark_town_encoded'] = pd.factorize(df_titanic['embark_town'])[0]
df_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group,sex_encoded,class_encoded,embark_town_encoded
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,young_adult,0,0,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,adult,1,1,1
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,young_adult,1,0,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,young_adult,1,1,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,C,Southampton,no,True,young_adult,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,C,Southampton,no,True,young_adult,0,2,0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,young_adult,1,1,0
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False,unknown,1,0,0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,young_adult,0,1,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,C,Queenstown,no,True,young_adult,0,0,2